// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Macro_MAC_Acc4_top_compute_mac (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        xi_s_0_0_dout,
        xi_s_0_0_empty_n,
        xi_s_0_0_read,
        xi_s_0_01_dout,
        xi_s_0_01_empty_n,
        xi_s_0_01_read,
        xi_s_0_02_dout,
        xi_s_0_02_empty_n,
        xi_s_0_02_read,
        xi_s_0_03_dout,
        xi_s_0_03_empty_n,
        xi_s_0_03_read,
        xi_s_0_04_dout,
        xi_s_0_04_empty_n,
        xi_s_0_04_read,
        xi_s_0_05_dout,
        xi_s_0_05_empty_n,
        xi_s_0_05_read,
        xi_s_0_06_dout,
        xi_s_0_06_empty_n,
        xi_s_0_06_read,
        xi_s_0_07_dout,
        xi_s_0_07_empty_n,
        xi_s_0_07_read,
        mro_s_0_0_dout,
        mro_s_0_0_empty_n,
        mro_s_0_0_read,
        mro_s_0_08_dout,
        mro_s_0_08_empty_n,
        mro_s_0_08_read,
        mro_s_0_09_dout,
        mro_s_0_09_empty_n,
        mro_s_0_09_read,
        mro_s_0_010_dout,
        mro_s_0_010_empty_n,
        mro_s_0_010_read,
        mro_s_0_011_dout,
        mro_s_0_011_empty_n,
        mro_s_0_011_read,
        mro_s_0_012_dout,
        mro_s_0_012_empty_n,
        mro_s_0_012_read,
        mro_s_0_013_dout,
        mro_s_0_013_empty_n,
        mro_s_0_013_read,
        mro_s_0_014_dout,
        mro_s_0_014_empty_n,
        mro_s_0_014_read,
        qzeros_0_val8,
        qzeros_1_val16,
        qzeros_2_val24,
        qzeros_3_val32,
        qzeros_4_val40,
        qzeros_5_val48,
        qzeros_6_val56,
        qzeros_7_val64,
        qscale_0_val72,
        qscale_1_val81,
        qscale_2_val89,
        qscale_3_val98,
        qscale_4_val106,
        qscale_5_val115,
        qscale_6_val123,
        qscale_7_val132,
        pout_local_0_i,
        pout_local_0_o,
        pout_local_0_o_ap_vld,
        pout_local_1_i,
        pout_local_1_o,
        pout_local_1_o_ap_vld,
        pout_local_2_i,
        pout_local_2_o,
        pout_local_2_o_ap_vld,
        pout_local_3_i,
        pout_local_3_o,
        pout_local_3_o_ap_vld,
        pout_local_4_i,
        pout_local_4_o,
        pout_local_4_o_ap_vld,
        pout_local_5_i,
        pout_local_5_o,
        pout_local_5_o_ap_vld,
        pout_local_6_i,
        pout_local_6_o,
        pout_local_6_o_ap_vld,
        pout_local_7_i,
        pout_local_7_o,
        pout_local_7_o_ap_vld
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state28 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] xi_s_0_0_dout;
input   xi_s_0_0_empty_n;
output   xi_s_0_0_read;
input  [31:0] xi_s_0_01_dout;
input   xi_s_0_01_empty_n;
output   xi_s_0_01_read;
input  [31:0] xi_s_0_02_dout;
input   xi_s_0_02_empty_n;
output   xi_s_0_02_read;
input  [31:0] xi_s_0_03_dout;
input   xi_s_0_03_empty_n;
output   xi_s_0_03_read;
input  [31:0] xi_s_0_04_dout;
input   xi_s_0_04_empty_n;
output   xi_s_0_04_read;
input  [31:0] xi_s_0_05_dout;
input   xi_s_0_05_empty_n;
output   xi_s_0_05_read;
input  [31:0] xi_s_0_06_dout;
input   xi_s_0_06_empty_n;
output   xi_s_0_06_read;
input  [31:0] xi_s_0_07_dout;
input   xi_s_0_07_empty_n;
output   xi_s_0_07_read;
input  [31:0] mro_s_0_0_dout;
input   mro_s_0_0_empty_n;
output   mro_s_0_0_read;
input  [31:0] mro_s_0_08_dout;
input   mro_s_0_08_empty_n;
output   mro_s_0_08_read;
input  [31:0] mro_s_0_09_dout;
input   mro_s_0_09_empty_n;
output   mro_s_0_09_read;
input  [31:0] mro_s_0_010_dout;
input   mro_s_0_010_empty_n;
output   mro_s_0_010_read;
input  [31:0] mro_s_0_011_dout;
input   mro_s_0_011_empty_n;
output   mro_s_0_011_read;
input  [31:0] mro_s_0_012_dout;
input   mro_s_0_012_empty_n;
output   mro_s_0_012_read;
input  [31:0] mro_s_0_013_dout;
input   mro_s_0_013_empty_n;
output   mro_s_0_013_read;
input  [31:0] mro_s_0_014_dout;
input   mro_s_0_014_empty_n;
output   mro_s_0_014_read;
input  [3:0] qzeros_0_val8;
input  [3:0] qzeros_1_val16;
input  [3:0] qzeros_2_val24;
input  [3:0] qzeros_3_val32;
input  [3:0] qzeros_4_val40;
input  [3:0] qzeros_5_val48;
input  [3:0] qzeros_6_val56;
input  [3:0] qzeros_7_val64;
input  [31:0] qscale_0_val72;
input  [31:0] qscale_1_val81;
input  [31:0] qscale_2_val89;
input  [31:0] qscale_3_val98;
input  [31:0] qscale_4_val106;
input  [31:0] qscale_5_val115;
input  [31:0] qscale_6_val123;
input  [31:0] qscale_7_val132;
input  [31:0] pout_local_0_i;
output  [31:0] pout_local_0_o;
output   pout_local_0_o_ap_vld;
input  [31:0] pout_local_1_i;
output  [31:0] pout_local_1_o;
output   pout_local_1_o_ap_vld;
input  [31:0] pout_local_2_i;
output  [31:0] pout_local_2_o;
output   pout_local_2_o_ap_vld;
input  [31:0] pout_local_3_i;
output  [31:0] pout_local_3_o;
output   pout_local_3_o_ap_vld;
input  [31:0] pout_local_4_i;
output  [31:0] pout_local_4_o;
output   pout_local_4_o_ap_vld;
input  [31:0] pout_local_5_i;
output  [31:0] pout_local_5_o;
output   pout_local_5_o_ap_vld;
input  [31:0] pout_local_6_i;
output  [31:0] pout_local_6_o;
output   pout_local_6_o_ap_vld;
input  [31:0] pout_local_7_i;
output  [31:0] pout_local_7_o;
output   pout_local_7_o_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[31:0] pout_local_0_o;
reg pout_local_0_o_ap_vld;
reg[31:0] pout_local_1_o;
reg pout_local_1_o_ap_vld;
reg[31:0] pout_local_2_o;
reg pout_local_2_o_ap_vld;
reg[31:0] pout_local_3_o;
reg pout_local_3_o_ap_vld;
reg[31:0] pout_local_4_o;
reg pout_local_4_o_ap_vld;
reg[31:0] pout_local_5_o;
reg pout_local_5_o_ap_vld;
reg[31:0] pout_local_6_o;
reg pout_local_6_o_ap_vld;
reg[31:0] pout_local_7_o;
reg pout_local_7_o_ap_vld;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] pout_temp_reg_1499;
wire    ap_CS_fsm_state2;
reg   [31:0] pout_temp_1_reg_1504;
reg   [31:0] pout_temp_2_reg_1509;
reg   [31:0] pout_temp_3_reg_1514;
reg   [31:0] pout_temp_4_reg_1519;
reg   [31:0] pout_temp_5_reg_1524;
reg   [31:0] pout_temp_6_reg_1529;
reg   [31:0] pout_temp_7_reg_1534;
reg   [31:0] pout_temp_8_reg_1539;
reg   [31:0] pout_temp_9_reg_1544;
reg   [31:0] pout_temp_10_reg_1549;
reg   [31:0] pout_temp_11_reg_1554;
reg   [31:0] pout_temp_12_reg_1559;
reg   [31:0] pout_temp_13_reg_1564;
reg   [31:0] pout_temp_14_reg_1569;
reg   [31:0] pout_temp_15_reg_1574;
reg   [31:0] pout_temp_16_reg_1579;
reg   [31:0] pout_temp_17_reg_1584;
reg   [31:0] pout_temp_18_reg_1589;
reg   [31:0] pout_temp_19_reg_1594;
reg   [31:0] pout_temp_20_reg_1599;
reg   [31:0] pout_temp_21_reg_1604;
reg   [31:0] pout_temp_22_reg_1609;
reg   [31:0] pout_temp_23_reg_1614;
reg   [31:0] pout_temp_24_reg_1619;
reg   [31:0] pout_temp_25_reg_1624;
reg   [31:0] pout_temp_26_reg_1629;
reg   [31:0] pout_temp_27_reg_1634;
reg   [31:0] pout_temp_28_reg_1639;
reg   [31:0] pout_temp_29_reg_1644;
reg   [31:0] pout_temp_30_reg_1649;
reg   [31:0] pout_temp_31_reg_1654;
reg   [31:0] pout_temp_32_reg_1659;
reg   [31:0] pout_temp_33_reg_1664;
reg   [31:0] pout_temp_34_reg_1669;
reg   [31:0] pout_temp_35_reg_1674;
reg   [31:0] pout_temp_36_reg_1679;
reg   [31:0] pout_temp_37_reg_1684;
reg   [31:0] pout_temp_38_reg_1689;
reg   [31:0] pout_temp_39_reg_1694;
reg   [31:0] pout_temp_40_reg_1699;
reg   [31:0] pout_temp_41_reg_1704;
reg   [31:0] pout_temp_42_reg_1709;
reg   [31:0] pout_temp_43_reg_1714;
reg   [31:0] pout_temp_44_reg_1719;
reg   [31:0] pout_temp_45_reg_1724;
reg   [31:0] pout_temp_46_reg_1729;
reg   [31:0] pout_temp_47_reg_1734;
reg   [31:0] pout_temp_48_reg_1739;
reg   [31:0] pout_temp_49_reg_1744;
reg   [31:0] pout_temp_50_reg_1749;
reg   [31:0] pout_temp_51_reg_1754;
reg   [31:0] pout_temp_52_reg_1759;
reg   [31:0] pout_temp_53_reg_1764;
reg   [31:0] pout_temp_54_reg_1769;
reg   [31:0] pout_temp_55_reg_1774;
reg   [31:0] pout_temp_56_reg_1779;
reg   [31:0] pout_temp_57_reg_1784;
reg   [31:0] pout_temp_58_reg_1789;
reg   [31:0] pout_temp_59_reg_1794;
reg   [31:0] pout_temp_60_reg_1799;
reg   [31:0] pout_temp_61_reg_1804;
reg   [31:0] pout_temp_62_reg_1809;
reg   [31:0] pout_temp_63_reg_1814;
wire   [2:0] trunc_ln235_fu_996_p1;
reg   [2:0] trunc_ln235_reg_1822;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_pp0_stage0_11001;
reg   [2:0] trunc_ln235_reg_1822_pp0_iter1_reg;
reg   [2:0] trunc_ln235_reg_1822_pp0_iter2_reg;
reg   [2:0] trunc_ln235_reg_1822_pp0_iter3_reg;
reg   [2:0] trunc_ln235_reg_1822_pp0_iter4_reg;
reg   [2:0] trunc_ln235_reg_1822_pp0_iter5_reg;
reg   [2:0] trunc_ln235_reg_1822_pp0_iter6_reg;
reg   [2:0] trunc_ln235_reg_1822_pp0_iter7_reg;
reg   [2:0] trunc_ln235_reg_1822_pp0_iter8_reg;
reg   [2:0] trunc_ln235_reg_1822_pp0_iter9_reg;
reg   [2:0] trunc_ln235_reg_1822_pp0_iter10_reg;
reg   [2:0] trunc_ln235_reg_1822_pp0_iter11_reg;
reg   [2:0] trunc_ln235_reg_1822_pp0_iter12_reg;
reg   [2:0] trunc_ln235_reg_1822_pp0_iter13_reg;
reg   [2:0] trunc_ln235_reg_1822_pp0_iter14_reg;
reg   [2:0] trunc_ln235_reg_1822_pp0_iter15_reg;
reg   [2:0] trunc_ln235_reg_1822_pp0_iter16_reg;
reg   [2:0] trunc_ln235_reg_1822_pp0_iter17_reg;
reg   [2:0] trunc_ln235_reg_1822_pp0_iter18_reg;
reg   [2:0] trunc_ln235_reg_1822_pp0_iter19_reg;
reg   [2:0] trunc_ln235_reg_1822_pp0_iter20_reg;
reg   [2:0] trunc_ln235_reg_1822_pp0_iter21_reg;
reg   [2:0] trunc_ln235_reg_1822_pp0_iter22_reg;
reg   [2:0] trunc_ln235_reg_1822_pp0_iter23_reg;
wire   [31:0] tmp_fu_1000_p19;
reg   [31:0] tmp_reg_1827;
wire   [31:0] tmp_8_fu_1032_p19;
reg   [31:0] tmp_8_reg_1832;
wire   [31:0] tmp_9_fu_1064_p19;
reg   [31:0] tmp_9_reg_1837;
wire   [31:0] tmp_s_fu_1096_p19;
reg   [31:0] tmp_s_reg_1842;
wire   [31:0] tmp_1_fu_1128_p19;
reg   [31:0] tmp_1_reg_1847;
wire   [31:0] tmp_2_fu_1160_p19;
reg   [31:0] tmp_2_reg_1852;
wire   [31:0] tmp_3_fu_1192_p19;
reg   [31:0] tmp_3_reg_1857;
wire   [31:0] tmp_4_fu_1224_p19;
reg   [31:0] tmp_4_reg_1862;
wire   [31:0] grp_fu_680_p2;
reg   [31:0] add_reg_1867;
wire   [31:0] grp_fu_684_p2;
reg   [31:0] add1_reg_1872;
wire   [31:0] grp_fu_688_p2;
reg   [31:0] add2_reg_1877;
wire   [31:0] grp_fu_692_p2;
reg   [31:0] add3_reg_1882;
wire   [31:0] grp_fu_696_p2;
reg   [31:0] add4_reg_1887;
wire   [31:0] grp_fu_700_p2;
reg   [31:0] add5_reg_1892;
wire   [31:0] grp_fu_704_p2;
reg   [31:0] final_sum_reg_1897;
wire   [31:0] tmp_5_fu_1261_p19;
reg   [31:0] tmp_5_reg_1902;
reg    ap_enable_reg_pp0_iter0;
wire    grp_compute_mac_sub_fu_360_ap_done;
wire    grp_compute_mac_sub_fu_400_ap_done;
wire    grp_compute_mac_sub_fu_440_ap_done;
wire    grp_compute_mac_sub_fu_480_ap_done;
wire    grp_compute_mac_sub_fu_520_ap_done;
wire    grp_compute_mac_sub_fu_560_ap_done;
wire    grp_compute_mac_sub_fu_600_ap_done;
wire    grp_compute_mac_sub_fu_640_ap_done;
reg    ap_block_state2_on_subcall_done;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln235_fu_984_p2;
reg    ap_condition_pp0_exit_iter0_state3;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
wire    grp_compute_mac_sub_fu_360_ap_start;
wire    grp_compute_mac_sub_fu_360_ap_idle;
wire    grp_compute_mac_sub_fu_360_ap_ready;
wire    grp_compute_mac_sub_fu_360_xi_s_0_read;
wire    grp_compute_mac_sub_fu_360_mro_s_0_read;
wire   [31:0] grp_compute_mac_sub_fu_360_ap_return_0;
wire   [31:0] grp_compute_mac_sub_fu_360_ap_return_1;
wire   [31:0] grp_compute_mac_sub_fu_360_ap_return_2;
wire   [31:0] grp_compute_mac_sub_fu_360_ap_return_3;
wire   [31:0] grp_compute_mac_sub_fu_360_ap_return_4;
wire   [31:0] grp_compute_mac_sub_fu_360_ap_return_5;
wire   [31:0] grp_compute_mac_sub_fu_360_ap_return_6;
wire   [31:0] grp_compute_mac_sub_fu_360_ap_return_7;
wire    grp_compute_mac_sub_fu_400_ap_start;
wire    grp_compute_mac_sub_fu_400_ap_idle;
wire    grp_compute_mac_sub_fu_400_ap_ready;
wire    grp_compute_mac_sub_fu_400_xi_s_0_read;
wire    grp_compute_mac_sub_fu_400_mro_s_0_read;
wire   [31:0] grp_compute_mac_sub_fu_400_ap_return_0;
wire   [31:0] grp_compute_mac_sub_fu_400_ap_return_1;
wire   [31:0] grp_compute_mac_sub_fu_400_ap_return_2;
wire   [31:0] grp_compute_mac_sub_fu_400_ap_return_3;
wire   [31:0] grp_compute_mac_sub_fu_400_ap_return_4;
wire   [31:0] grp_compute_mac_sub_fu_400_ap_return_5;
wire   [31:0] grp_compute_mac_sub_fu_400_ap_return_6;
wire   [31:0] grp_compute_mac_sub_fu_400_ap_return_7;
wire    grp_compute_mac_sub_fu_440_ap_start;
wire    grp_compute_mac_sub_fu_440_ap_idle;
wire    grp_compute_mac_sub_fu_440_ap_ready;
wire    grp_compute_mac_sub_fu_440_xi_s_0_read;
wire    grp_compute_mac_sub_fu_440_mro_s_0_read;
wire   [31:0] grp_compute_mac_sub_fu_440_ap_return_0;
wire   [31:0] grp_compute_mac_sub_fu_440_ap_return_1;
wire   [31:0] grp_compute_mac_sub_fu_440_ap_return_2;
wire   [31:0] grp_compute_mac_sub_fu_440_ap_return_3;
wire   [31:0] grp_compute_mac_sub_fu_440_ap_return_4;
wire   [31:0] grp_compute_mac_sub_fu_440_ap_return_5;
wire   [31:0] grp_compute_mac_sub_fu_440_ap_return_6;
wire   [31:0] grp_compute_mac_sub_fu_440_ap_return_7;
wire    grp_compute_mac_sub_fu_480_ap_start;
wire    grp_compute_mac_sub_fu_480_ap_idle;
wire    grp_compute_mac_sub_fu_480_ap_ready;
wire    grp_compute_mac_sub_fu_480_xi_s_0_read;
wire    grp_compute_mac_sub_fu_480_mro_s_0_read;
wire   [31:0] grp_compute_mac_sub_fu_480_ap_return_0;
wire   [31:0] grp_compute_mac_sub_fu_480_ap_return_1;
wire   [31:0] grp_compute_mac_sub_fu_480_ap_return_2;
wire   [31:0] grp_compute_mac_sub_fu_480_ap_return_3;
wire   [31:0] grp_compute_mac_sub_fu_480_ap_return_4;
wire   [31:0] grp_compute_mac_sub_fu_480_ap_return_5;
wire   [31:0] grp_compute_mac_sub_fu_480_ap_return_6;
wire   [31:0] grp_compute_mac_sub_fu_480_ap_return_7;
wire    grp_compute_mac_sub_fu_520_ap_start;
wire    grp_compute_mac_sub_fu_520_ap_idle;
wire    grp_compute_mac_sub_fu_520_ap_ready;
wire    grp_compute_mac_sub_fu_520_xi_s_0_read;
wire    grp_compute_mac_sub_fu_520_mro_s_0_read;
wire   [31:0] grp_compute_mac_sub_fu_520_ap_return_0;
wire   [31:0] grp_compute_mac_sub_fu_520_ap_return_1;
wire   [31:0] grp_compute_mac_sub_fu_520_ap_return_2;
wire   [31:0] grp_compute_mac_sub_fu_520_ap_return_3;
wire   [31:0] grp_compute_mac_sub_fu_520_ap_return_4;
wire   [31:0] grp_compute_mac_sub_fu_520_ap_return_5;
wire   [31:0] grp_compute_mac_sub_fu_520_ap_return_6;
wire   [31:0] grp_compute_mac_sub_fu_520_ap_return_7;
wire    grp_compute_mac_sub_fu_560_ap_start;
wire    grp_compute_mac_sub_fu_560_ap_idle;
wire    grp_compute_mac_sub_fu_560_ap_ready;
wire    grp_compute_mac_sub_fu_560_xi_s_0_read;
wire    grp_compute_mac_sub_fu_560_mro_s_0_read;
wire   [31:0] grp_compute_mac_sub_fu_560_ap_return_0;
wire   [31:0] grp_compute_mac_sub_fu_560_ap_return_1;
wire   [31:0] grp_compute_mac_sub_fu_560_ap_return_2;
wire   [31:0] grp_compute_mac_sub_fu_560_ap_return_3;
wire   [31:0] grp_compute_mac_sub_fu_560_ap_return_4;
wire   [31:0] grp_compute_mac_sub_fu_560_ap_return_5;
wire   [31:0] grp_compute_mac_sub_fu_560_ap_return_6;
wire   [31:0] grp_compute_mac_sub_fu_560_ap_return_7;
wire    grp_compute_mac_sub_fu_600_ap_start;
wire    grp_compute_mac_sub_fu_600_ap_idle;
wire    grp_compute_mac_sub_fu_600_ap_ready;
wire    grp_compute_mac_sub_fu_600_xi_s_0_read;
wire    grp_compute_mac_sub_fu_600_mro_s_0_read;
wire   [31:0] grp_compute_mac_sub_fu_600_ap_return_0;
wire   [31:0] grp_compute_mac_sub_fu_600_ap_return_1;
wire   [31:0] grp_compute_mac_sub_fu_600_ap_return_2;
wire   [31:0] grp_compute_mac_sub_fu_600_ap_return_3;
wire   [31:0] grp_compute_mac_sub_fu_600_ap_return_4;
wire   [31:0] grp_compute_mac_sub_fu_600_ap_return_5;
wire   [31:0] grp_compute_mac_sub_fu_600_ap_return_6;
wire   [31:0] grp_compute_mac_sub_fu_600_ap_return_7;
wire    grp_compute_mac_sub_fu_640_ap_start;
wire    grp_compute_mac_sub_fu_640_ap_idle;
wire    grp_compute_mac_sub_fu_640_ap_ready;
wire    grp_compute_mac_sub_fu_640_xi_s_0_read;
wire    grp_compute_mac_sub_fu_640_mro_s_0_read;
wire   [31:0] grp_compute_mac_sub_fu_640_ap_return_0;
wire   [31:0] grp_compute_mac_sub_fu_640_ap_return_1;
wire   [31:0] grp_compute_mac_sub_fu_640_ap_return_2;
wire   [31:0] grp_compute_mac_sub_fu_640_ap_return_3;
wire   [31:0] grp_compute_mac_sub_fu_640_ap_return_4;
wire   [31:0] grp_compute_mac_sub_fu_640_ap_return_5;
wire   [31:0] grp_compute_mac_sub_fu_640_ap_return_6;
wire   [31:0] grp_compute_mac_sub_fu_640_ap_return_7;
reg    grp_compute_mac_sub_fu_360_ap_start_reg;
reg    grp_compute_mac_sub_fu_400_ap_start_reg;
reg    grp_compute_mac_sub_fu_440_ap_start_reg;
reg    grp_compute_mac_sub_fu_480_ap_start_reg;
reg    grp_compute_mac_sub_fu_520_ap_start_reg;
reg    grp_compute_mac_sub_fu_560_ap_start_reg;
reg    grp_compute_mac_sub_fu_600_ap_start_reg;
reg    grp_compute_mac_sub_fu_640_ap_start_reg;
reg   [3:0] j_fu_156;
wire   [3:0] add_ln235_fu_990_p2;
wire    ap_block_pp0_stage0;
wire   [31:0] grp_fu_708_p2;
wire    ap_block_pp0_stage0_01001;
wire   [31:0] tmp_fu_1000_p17;
wire   [31:0] tmp_8_fu_1032_p17;
wire   [31:0] tmp_9_fu_1064_p17;
wire   [31:0] tmp_s_fu_1096_p17;
wire   [31:0] tmp_1_fu_1128_p17;
wire   [31:0] tmp_2_fu_1160_p17;
wire   [31:0] tmp_3_fu_1192_p17;
wire   [31:0] tmp_4_fu_1224_p17;
wire   [31:0] tmp_5_fu_1261_p17;
wire    ap_CS_fsm_state28;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state28_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [2:0] tmp_fu_1000_p1;
wire   [2:0] tmp_fu_1000_p3;
wire   [2:0] tmp_fu_1000_p5;
wire   [2:0] tmp_fu_1000_p7;
wire  signed [2:0] tmp_fu_1000_p9;
wire  signed [2:0] tmp_fu_1000_p11;
wire  signed [2:0] tmp_fu_1000_p13;
wire  signed [2:0] tmp_fu_1000_p15;
wire   [2:0] tmp_8_fu_1032_p1;
wire   [2:0] tmp_8_fu_1032_p3;
wire   [2:0] tmp_8_fu_1032_p5;
wire   [2:0] tmp_8_fu_1032_p7;
wire  signed [2:0] tmp_8_fu_1032_p9;
wire  signed [2:0] tmp_8_fu_1032_p11;
wire  signed [2:0] tmp_8_fu_1032_p13;
wire  signed [2:0] tmp_8_fu_1032_p15;
wire   [2:0] tmp_9_fu_1064_p1;
wire   [2:0] tmp_9_fu_1064_p3;
wire   [2:0] tmp_9_fu_1064_p5;
wire   [2:0] tmp_9_fu_1064_p7;
wire  signed [2:0] tmp_9_fu_1064_p9;
wire  signed [2:0] tmp_9_fu_1064_p11;
wire  signed [2:0] tmp_9_fu_1064_p13;
wire  signed [2:0] tmp_9_fu_1064_p15;
wire   [2:0] tmp_s_fu_1096_p1;
wire   [2:0] tmp_s_fu_1096_p3;
wire   [2:0] tmp_s_fu_1096_p5;
wire   [2:0] tmp_s_fu_1096_p7;
wire  signed [2:0] tmp_s_fu_1096_p9;
wire  signed [2:0] tmp_s_fu_1096_p11;
wire  signed [2:0] tmp_s_fu_1096_p13;
wire  signed [2:0] tmp_s_fu_1096_p15;
wire   [2:0] tmp_1_fu_1128_p1;
wire   [2:0] tmp_1_fu_1128_p3;
wire   [2:0] tmp_1_fu_1128_p5;
wire   [2:0] tmp_1_fu_1128_p7;
wire  signed [2:0] tmp_1_fu_1128_p9;
wire  signed [2:0] tmp_1_fu_1128_p11;
wire  signed [2:0] tmp_1_fu_1128_p13;
wire  signed [2:0] tmp_1_fu_1128_p15;
wire   [2:0] tmp_2_fu_1160_p1;
wire   [2:0] tmp_2_fu_1160_p3;
wire   [2:0] tmp_2_fu_1160_p5;
wire   [2:0] tmp_2_fu_1160_p7;
wire  signed [2:0] tmp_2_fu_1160_p9;
wire  signed [2:0] tmp_2_fu_1160_p11;
wire  signed [2:0] tmp_2_fu_1160_p13;
wire  signed [2:0] tmp_2_fu_1160_p15;
wire   [2:0] tmp_3_fu_1192_p1;
wire   [2:0] tmp_3_fu_1192_p3;
wire   [2:0] tmp_3_fu_1192_p5;
wire   [2:0] tmp_3_fu_1192_p7;
wire  signed [2:0] tmp_3_fu_1192_p9;
wire  signed [2:0] tmp_3_fu_1192_p11;
wire  signed [2:0] tmp_3_fu_1192_p13;
wire  signed [2:0] tmp_3_fu_1192_p15;
wire   [2:0] tmp_4_fu_1224_p1;
wire   [2:0] tmp_4_fu_1224_p3;
wire   [2:0] tmp_4_fu_1224_p5;
wire   [2:0] tmp_4_fu_1224_p7;
wire  signed [2:0] tmp_4_fu_1224_p9;
wire  signed [2:0] tmp_4_fu_1224_p11;
wire  signed [2:0] tmp_4_fu_1224_p13;
wire  signed [2:0] tmp_4_fu_1224_p15;
wire   [2:0] tmp_5_fu_1261_p1;
wire   [2:0] tmp_5_fu_1261_p3;
wire   [2:0] tmp_5_fu_1261_p5;
wire   [2:0] tmp_5_fu_1261_p7;
wire  signed [2:0] tmp_5_fu_1261_p9;
wire  signed [2:0] tmp_5_fu_1261_p11;
wire  signed [2:0] tmp_5_fu_1261_p13;
wire  signed [2:0] tmp_5_fu_1261_p15;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 grp_compute_mac_sub_fu_360_ap_start_reg = 1'b0;
#0 grp_compute_mac_sub_fu_400_ap_start_reg = 1'b0;
#0 grp_compute_mac_sub_fu_440_ap_start_reg = 1'b0;
#0 grp_compute_mac_sub_fu_480_ap_start_reg = 1'b0;
#0 grp_compute_mac_sub_fu_520_ap_start_reg = 1'b0;
#0 grp_compute_mac_sub_fu_560_ap_start_reg = 1'b0;
#0 grp_compute_mac_sub_fu_600_ap_start_reg = 1'b0;
#0 grp_compute_mac_sub_fu_640_ap_start_reg = 1'b0;
#0 j_fu_156 = 4'd0;
end

Macro_MAC_Acc4_top_compute_mac_sub grp_compute_mac_sub_fu_360(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_mac_sub_fu_360_ap_start),
    .ap_done(grp_compute_mac_sub_fu_360_ap_done),
    .ap_idle(grp_compute_mac_sub_fu_360_ap_idle),
    .ap_ready(grp_compute_mac_sub_fu_360_ap_ready),
    .xi_s_0_dout(xi_s_0_0_dout),
    .xi_s_0_empty_n(xi_s_0_0_empty_n),
    .xi_s_0_read(grp_compute_mac_sub_fu_360_xi_s_0_read),
    .mro_s_0_dout(mro_s_0_0_dout),
    .mro_s_0_empty_n(mro_s_0_0_empty_n),
    .mro_s_0_read(grp_compute_mac_sub_fu_360_mro_s_0_read),
    .qzeros_0_val(qzeros_0_val8),
    .qzeros_1_val(qzeros_1_val16),
    .qzeros_2_val(qzeros_2_val24),
    .qzeros_3_val(qzeros_3_val32),
    .qzeros_4_val(qzeros_4_val40),
    .qzeros_5_val(qzeros_5_val48),
    .qzeros_6_val(qzeros_6_val56),
    .qzeros_7_val(qzeros_7_val64),
    .qscale_0_val(qscale_0_val72),
    .qscale_1_val(qscale_1_val81),
    .qscale_2_val(qscale_2_val89),
    .qscale_3_val(qscale_3_val98),
    .qscale_4_val(qscale_4_val106),
    .qscale_5_val(qscale_5_val115),
    .qscale_6_val(qscale_6_val123),
    .qscale_7_val(qscale_7_val132),
    .ap_return_0(grp_compute_mac_sub_fu_360_ap_return_0),
    .ap_return_1(grp_compute_mac_sub_fu_360_ap_return_1),
    .ap_return_2(grp_compute_mac_sub_fu_360_ap_return_2),
    .ap_return_3(grp_compute_mac_sub_fu_360_ap_return_3),
    .ap_return_4(grp_compute_mac_sub_fu_360_ap_return_4),
    .ap_return_5(grp_compute_mac_sub_fu_360_ap_return_5),
    .ap_return_6(grp_compute_mac_sub_fu_360_ap_return_6),
    .ap_return_7(grp_compute_mac_sub_fu_360_ap_return_7)
);

Macro_MAC_Acc4_top_compute_mac_sub grp_compute_mac_sub_fu_400(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_mac_sub_fu_400_ap_start),
    .ap_done(grp_compute_mac_sub_fu_400_ap_done),
    .ap_idle(grp_compute_mac_sub_fu_400_ap_idle),
    .ap_ready(grp_compute_mac_sub_fu_400_ap_ready),
    .xi_s_0_dout(xi_s_0_01_dout),
    .xi_s_0_empty_n(xi_s_0_01_empty_n),
    .xi_s_0_read(grp_compute_mac_sub_fu_400_xi_s_0_read),
    .mro_s_0_dout(mro_s_0_08_dout),
    .mro_s_0_empty_n(mro_s_0_08_empty_n),
    .mro_s_0_read(grp_compute_mac_sub_fu_400_mro_s_0_read),
    .qzeros_0_val(qzeros_0_val8),
    .qzeros_1_val(qzeros_1_val16),
    .qzeros_2_val(qzeros_2_val24),
    .qzeros_3_val(qzeros_3_val32),
    .qzeros_4_val(qzeros_4_val40),
    .qzeros_5_val(qzeros_5_val48),
    .qzeros_6_val(qzeros_6_val56),
    .qzeros_7_val(qzeros_7_val64),
    .qscale_0_val(qscale_0_val72),
    .qscale_1_val(qscale_1_val81),
    .qscale_2_val(qscale_2_val89),
    .qscale_3_val(qscale_3_val98),
    .qscale_4_val(qscale_4_val106),
    .qscale_5_val(qscale_5_val115),
    .qscale_6_val(qscale_6_val123),
    .qscale_7_val(qscale_7_val132),
    .ap_return_0(grp_compute_mac_sub_fu_400_ap_return_0),
    .ap_return_1(grp_compute_mac_sub_fu_400_ap_return_1),
    .ap_return_2(grp_compute_mac_sub_fu_400_ap_return_2),
    .ap_return_3(grp_compute_mac_sub_fu_400_ap_return_3),
    .ap_return_4(grp_compute_mac_sub_fu_400_ap_return_4),
    .ap_return_5(grp_compute_mac_sub_fu_400_ap_return_5),
    .ap_return_6(grp_compute_mac_sub_fu_400_ap_return_6),
    .ap_return_7(grp_compute_mac_sub_fu_400_ap_return_7)
);

Macro_MAC_Acc4_top_compute_mac_sub grp_compute_mac_sub_fu_440(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_mac_sub_fu_440_ap_start),
    .ap_done(grp_compute_mac_sub_fu_440_ap_done),
    .ap_idle(grp_compute_mac_sub_fu_440_ap_idle),
    .ap_ready(grp_compute_mac_sub_fu_440_ap_ready),
    .xi_s_0_dout(xi_s_0_02_dout),
    .xi_s_0_empty_n(xi_s_0_02_empty_n),
    .xi_s_0_read(grp_compute_mac_sub_fu_440_xi_s_0_read),
    .mro_s_0_dout(mro_s_0_09_dout),
    .mro_s_0_empty_n(mro_s_0_09_empty_n),
    .mro_s_0_read(grp_compute_mac_sub_fu_440_mro_s_0_read),
    .qzeros_0_val(qzeros_0_val8),
    .qzeros_1_val(qzeros_1_val16),
    .qzeros_2_val(qzeros_2_val24),
    .qzeros_3_val(qzeros_3_val32),
    .qzeros_4_val(qzeros_4_val40),
    .qzeros_5_val(qzeros_5_val48),
    .qzeros_6_val(qzeros_6_val56),
    .qzeros_7_val(qzeros_7_val64),
    .qscale_0_val(qscale_0_val72),
    .qscale_1_val(qscale_1_val81),
    .qscale_2_val(qscale_2_val89),
    .qscale_3_val(qscale_3_val98),
    .qscale_4_val(qscale_4_val106),
    .qscale_5_val(qscale_5_val115),
    .qscale_6_val(qscale_6_val123),
    .qscale_7_val(qscale_7_val132),
    .ap_return_0(grp_compute_mac_sub_fu_440_ap_return_0),
    .ap_return_1(grp_compute_mac_sub_fu_440_ap_return_1),
    .ap_return_2(grp_compute_mac_sub_fu_440_ap_return_2),
    .ap_return_3(grp_compute_mac_sub_fu_440_ap_return_3),
    .ap_return_4(grp_compute_mac_sub_fu_440_ap_return_4),
    .ap_return_5(grp_compute_mac_sub_fu_440_ap_return_5),
    .ap_return_6(grp_compute_mac_sub_fu_440_ap_return_6),
    .ap_return_7(grp_compute_mac_sub_fu_440_ap_return_7)
);

Macro_MAC_Acc4_top_compute_mac_sub grp_compute_mac_sub_fu_480(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_mac_sub_fu_480_ap_start),
    .ap_done(grp_compute_mac_sub_fu_480_ap_done),
    .ap_idle(grp_compute_mac_sub_fu_480_ap_idle),
    .ap_ready(grp_compute_mac_sub_fu_480_ap_ready),
    .xi_s_0_dout(xi_s_0_03_dout),
    .xi_s_0_empty_n(xi_s_0_03_empty_n),
    .xi_s_0_read(grp_compute_mac_sub_fu_480_xi_s_0_read),
    .mro_s_0_dout(mro_s_0_010_dout),
    .mro_s_0_empty_n(mro_s_0_010_empty_n),
    .mro_s_0_read(grp_compute_mac_sub_fu_480_mro_s_0_read),
    .qzeros_0_val(qzeros_0_val8),
    .qzeros_1_val(qzeros_1_val16),
    .qzeros_2_val(qzeros_2_val24),
    .qzeros_3_val(qzeros_3_val32),
    .qzeros_4_val(qzeros_4_val40),
    .qzeros_5_val(qzeros_5_val48),
    .qzeros_6_val(qzeros_6_val56),
    .qzeros_7_val(qzeros_7_val64),
    .qscale_0_val(qscale_0_val72),
    .qscale_1_val(qscale_1_val81),
    .qscale_2_val(qscale_2_val89),
    .qscale_3_val(qscale_3_val98),
    .qscale_4_val(qscale_4_val106),
    .qscale_5_val(qscale_5_val115),
    .qscale_6_val(qscale_6_val123),
    .qscale_7_val(qscale_7_val132),
    .ap_return_0(grp_compute_mac_sub_fu_480_ap_return_0),
    .ap_return_1(grp_compute_mac_sub_fu_480_ap_return_1),
    .ap_return_2(grp_compute_mac_sub_fu_480_ap_return_2),
    .ap_return_3(grp_compute_mac_sub_fu_480_ap_return_3),
    .ap_return_4(grp_compute_mac_sub_fu_480_ap_return_4),
    .ap_return_5(grp_compute_mac_sub_fu_480_ap_return_5),
    .ap_return_6(grp_compute_mac_sub_fu_480_ap_return_6),
    .ap_return_7(grp_compute_mac_sub_fu_480_ap_return_7)
);

Macro_MAC_Acc4_top_compute_mac_sub grp_compute_mac_sub_fu_520(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_mac_sub_fu_520_ap_start),
    .ap_done(grp_compute_mac_sub_fu_520_ap_done),
    .ap_idle(grp_compute_mac_sub_fu_520_ap_idle),
    .ap_ready(grp_compute_mac_sub_fu_520_ap_ready),
    .xi_s_0_dout(xi_s_0_04_dout),
    .xi_s_0_empty_n(xi_s_0_04_empty_n),
    .xi_s_0_read(grp_compute_mac_sub_fu_520_xi_s_0_read),
    .mro_s_0_dout(mro_s_0_011_dout),
    .mro_s_0_empty_n(mro_s_0_011_empty_n),
    .mro_s_0_read(grp_compute_mac_sub_fu_520_mro_s_0_read),
    .qzeros_0_val(qzeros_0_val8),
    .qzeros_1_val(qzeros_1_val16),
    .qzeros_2_val(qzeros_2_val24),
    .qzeros_3_val(qzeros_3_val32),
    .qzeros_4_val(qzeros_4_val40),
    .qzeros_5_val(qzeros_5_val48),
    .qzeros_6_val(qzeros_6_val56),
    .qzeros_7_val(qzeros_7_val64),
    .qscale_0_val(qscale_0_val72),
    .qscale_1_val(qscale_1_val81),
    .qscale_2_val(qscale_2_val89),
    .qscale_3_val(qscale_3_val98),
    .qscale_4_val(qscale_4_val106),
    .qscale_5_val(qscale_5_val115),
    .qscale_6_val(qscale_6_val123),
    .qscale_7_val(qscale_7_val132),
    .ap_return_0(grp_compute_mac_sub_fu_520_ap_return_0),
    .ap_return_1(grp_compute_mac_sub_fu_520_ap_return_1),
    .ap_return_2(grp_compute_mac_sub_fu_520_ap_return_2),
    .ap_return_3(grp_compute_mac_sub_fu_520_ap_return_3),
    .ap_return_4(grp_compute_mac_sub_fu_520_ap_return_4),
    .ap_return_5(grp_compute_mac_sub_fu_520_ap_return_5),
    .ap_return_6(grp_compute_mac_sub_fu_520_ap_return_6),
    .ap_return_7(grp_compute_mac_sub_fu_520_ap_return_7)
);

Macro_MAC_Acc4_top_compute_mac_sub grp_compute_mac_sub_fu_560(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_mac_sub_fu_560_ap_start),
    .ap_done(grp_compute_mac_sub_fu_560_ap_done),
    .ap_idle(grp_compute_mac_sub_fu_560_ap_idle),
    .ap_ready(grp_compute_mac_sub_fu_560_ap_ready),
    .xi_s_0_dout(xi_s_0_05_dout),
    .xi_s_0_empty_n(xi_s_0_05_empty_n),
    .xi_s_0_read(grp_compute_mac_sub_fu_560_xi_s_0_read),
    .mro_s_0_dout(mro_s_0_012_dout),
    .mro_s_0_empty_n(mro_s_0_012_empty_n),
    .mro_s_0_read(grp_compute_mac_sub_fu_560_mro_s_0_read),
    .qzeros_0_val(qzeros_0_val8),
    .qzeros_1_val(qzeros_1_val16),
    .qzeros_2_val(qzeros_2_val24),
    .qzeros_3_val(qzeros_3_val32),
    .qzeros_4_val(qzeros_4_val40),
    .qzeros_5_val(qzeros_5_val48),
    .qzeros_6_val(qzeros_6_val56),
    .qzeros_7_val(qzeros_7_val64),
    .qscale_0_val(qscale_0_val72),
    .qscale_1_val(qscale_1_val81),
    .qscale_2_val(qscale_2_val89),
    .qscale_3_val(qscale_3_val98),
    .qscale_4_val(qscale_4_val106),
    .qscale_5_val(qscale_5_val115),
    .qscale_6_val(qscale_6_val123),
    .qscale_7_val(qscale_7_val132),
    .ap_return_0(grp_compute_mac_sub_fu_560_ap_return_0),
    .ap_return_1(grp_compute_mac_sub_fu_560_ap_return_1),
    .ap_return_2(grp_compute_mac_sub_fu_560_ap_return_2),
    .ap_return_3(grp_compute_mac_sub_fu_560_ap_return_3),
    .ap_return_4(grp_compute_mac_sub_fu_560_ap_return_4),
    .ap_return_5(grp_compute_mac_sub_fu_560_ap_return_5),
    .ap_return_6(grp_compute_mac_sub_fu_560_ap_return_6),
    .ap_return_7(grp_compute_mac_sub_fu_560_ap_return_7)
);

Macro_MAC_Acc4_top_compute_mac_sub grp_compute_mac_sub_fu_600(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_mac_sub_fu_600_ap_start),
    .ap_done(grp_compute_mac_sub_fu_600_ap_done),
    .ap_idle(grp_compute_mac_sub_fu_600_ap_idle),
    .ap_ready(grp_compute_mac_sub_fu_600_ap_ready),
    .xi_s_0_dout(xi_s_0_06_dout),
    .xi_s_0_empty_n(xi_s_0_06_empty_n),
    .xi_s_0_read(grp_compute_mac_sub_fu_600_xi_s_0_read),
    .mro_s_0_dout(mro_s_0_013_dout),
    .mro_s_0_empty_n(mro_s_0_013_empty_n),
    .mro_s_0_read(grp_compute_mac_sub_fu_600_mro_s_0_read),
    .qzeros_0_val(qzeros_0_val8),
    .qzeros_1_val(qzeros_1_val16),
    .qzeros_2_val(qzeros_2_val24),
    .qzeros_3_val(qzeros_3_val32),
    .qzeros_4_val(qzeros_4_val40),
    .qzeros_5_val(qzeros_5_val48),
    .qzeros_6_val(qzeros_6_val56),
    .qzeros_7_val(qzeros_7_val64),
    .qscale_0_val(qscale_0_val72),
    .qscale_1_val(qscale_1_val81),
    .qscale_2_val(qscale_2_val89),
    .qscale_3_val(qscale_3_val98),
    .qscale_4_val(qscale_4_val106),
    .qscale_5_val(qscale_5_val115),
    .qscale_6_val(qscale_6_val123),
    .qscale_7_val(qscale_7_val132),
    .ap_return_0(grp_compute_mac_sub_fu_600_ap_return_0),
    .ap_return_1(grp_compute_mac_sub_fu_600_ap_return_1),
    .ap_return_2(grp_compute_mac_sub_fu_600_ap_return_2),
    .ap_return_3(grp_compute_mac_sub_fu_600_ap_return_3),
    .ap_return_4(grp_compute_mac_sub_fu_600_ap_return_4),
    .ap_return_5(grp_compute_mac_sub_fu_600_ap_return_5),
    .ap_return_6(grp_compute_mac_sub_fu_600_ap_return_6),
    .ap_return_7(grp_compute_mac_sub_fu_600_ap_return_7)
);

Macro_MAC_Acc4_top_compute_mac_sub grp_compute_mac_sub_fu_640(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_mac_sub_fu_640_ap_start),
    .ap_done(grp_compute_mac_sub_fu_640_ap_done),
    .ap_idle(grp_compute_mac_sub_fu_640_ap_idle),
    .ap_ready(grp_compute_mac_sub_fu_640_ap_ready),
    .xi_s_0_dout(xi_s_0_07_dout),
    .xi_s_0_empty_n(xi_s_0_07_empty_n),
    .xi_s_0_read(grp_compute_mac_sub_fu_640_xi_s_0_read),
    .mro_s_0_dout(mro_s_0_014_dout),
    .mro_s_0_empty_n(mro_s_0_014_empty_n),
    .mro_s_0_read(grp_compute_mac_sub_fu_640_mro_s_0_read),
    .qzeros_0_val(qzeros_0_val8),
    .qzeros_1_val(qzeros_1_val16),
    .qzeros_2_val(qzeros_2_val24),
    .qzeros_3_val(qzeros_3_val32),
    .qzeros_4_val(qzeros_4_val40),
    .qzeros_5_val(qzeros_5_val48),
    .qzeros_6_val(qzeros_6_val56),
    .qzeros_7_val(qzeros_7_val64),
    .qscale_0_val(qscale_0_val72),
    .qscale_1_val(qscale_1_val81),
    .qscale_2_val(qscale_2_val89),
    .qscale_3_val(qscale_3_val98),
    .qscale_4_val(qscale_4_val106),
    .qscale_5_val(qscale_5_val115),
    .qscale_6_val(qscale_6_val123),
    .qscale_7_val(qscale_7_val132),
    .ap_return_0(grp_compute_mac_sub_fu_640_ap_return_0),
    .ap_return_1(grp_compute_mac_sub_fu_640_ap_return_1),
    .ap_return_2(grp_compute_mac_sub_fu_640_ap_return_2),
    .ap_return_3(grp_compute_mac_sub_fu_640_ap_return_3),
    .ap_return_4(grp_compute_mac_sub_fu_640_ap_return_4),
    .ap_return_5(grp_compute_mac_sub_fu_640_ap_return_5),
    .ap_return_6(grp_compute_mac_sub_fu_640_ap_return_6),
    .ap_return_7(grp_compute_mac_sub_fu_640_ap_return_7)
);

Macro_MAC_Acc4_top_fadd_32ns_32ns_32_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_6_no_dsp_1_U187(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_reg_1827),
    .din1(tmp_8_reg_1832),
    .ce(1'b1),
    .dout(grp_fu_680_p2)
);

Macro_MAC_Acc4_top_fadd_32ns_32ns_32_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_6_no_dsp_1_U188(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_9_reg_1837),
    .din1(tmp_s_reg_1842),
    .ce(1'b1),
    .dout(grp_fu_684_p2)
);

Macro_MAC_Acc4_top_fadd_32ns_32ns_32_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_6_no_dsp_1_U189(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_1_reg_1847),
    .din1(tmp_2_reg_1852),
    .ce(1'b1),
    .dout(grp_fu_688_p2)
);

Macro_MAC_Acc4_top_fadd_32ns_32ns_32_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_6_no_dsp_1_U190(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_3_reg_1857),
    .din1(tmp_4_reg_1862),
    .ce(1'b1),
    .dout(grp_fu_692_p2)
);

Macro_MAC_Acc4_top_fadd_32ns_32ns_32_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_6_no_dsp_1_U191(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_reg_1867),
    .din1(add1_reg_1872),
    .ce(1'b1),
    .dout(grp_fu_696_p2)
);

Macro_MAC_Acc4_top_fadd_32ns_32ns_32_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_6_no_dsp_1_U192(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add2_reg_1877),
    .din1(add3_reg_1882),
    .ce(1'b1),
    .dout(grp_fu_700_p2)
);

Macro_MAC_Acc4_top_fadd_32ns_32ns_32_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_6_no_dsp_1_U193(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add4_reg_1887),
    .din1(add5_reg_1892),
    .ce(1'b1),
    .dout(grp_fu_704_p2)
);

Macro_MAC_Acc4_top_fadd_32ns_32ns_32_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_6_no_dsp_1_U194(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_5_reg_1902),
    .din1(final_sum_reg_1897),
    .ce(1'b1),
    .dout(grp_fu_708_p2)
);

(* dissolve_hierarchy = "yes" *) Macro_MAC_Acc4_top_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U195(
    .din0(pout_temp_reg_1499),
    .din1(pout_temp_1_reg_1504),
    .din2(pout_temp_2_reg_1509),
    .din3(pout_temp_3_reg_1514),
    .din4(pout_temp_4_reg_1519),
    .din5(pout_temp_5_reg_1524),
    .din6(pout_temp_6_reg_1529),
    .din7(pout_temp_7_reg_1534),
    .def(tmp_fu_1000_p17),
    .sel(trunc_ln235_fu_996_p1),
    .dout(tmp_fu_1000_p19)
);

(* dissolve_hierarchy = "yes" *) Macro_MAC_Acc4_top_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U196(
    .din0(pout_temp_8_reg_1539),
    .din1(pout_temp_9_reg_1544),
    .din2(pout_temp_10_reg_1549),
    .din3(pout_temp_11_reg_1554),
    .din4(pout_temp_12_reg_1559),
    .din5(pout_temp_13_reg_1564),
    .din6(pout_temp_14_reg_1569),
    .din7(pout_temp_15_reg_1574),
    .def(tmp_8_fu_1032_p17),
    .sel(trunc_ln235_fu_996_p1),
    .dout(tmp_8_fu_1032_p19)
);

(* dissolve_hierarchy = "yes" *) Macro_MAC_Acc4_top_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U197(
    .din0(pout_temp_16_reg_1579),
    .din1(pout_temp_17_reg_1584),
    .din2(pout_temp_18_reg_1589),
    .din3(pout_temp_19_reg_1594),
    .din4(pout_temp_20_reg_1599),
    .din5(pout_temp_21_reg_1604),
    .din6(pout_temp_22_reg_1609),
    .din7(pout_temp_23_reg_1614),
    .def(tmp_9_fu_1064_p17),
    .sel(trunc_ln235_fu_996_p1),
    .dout(tmp_9_fu_1064_p19)
);

(* dissolve_hierarchy = "yes" *) Macro_MAC_Acc4_top_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U198(
    .din0(pout_temp_24_reg_1619),
    .din1(pout_temp_25_reg_1624),
    .din2(pout_temp_26_reg_1629),
    .din3(pout_temp_27_reg_1634),
    .din4(pout_temp_28_reg_1639),
    .din5(pout_temp_29_reg_1644),
    .din6(pout_temp_30_reg_1649),
    .din7(pout_temp_31_reg_1654),
    .def(tmp_s_fu_1096_p17),
    .sel(trunc_ln235_fu_996_p1),
    .dout(tmp_s_fu_1096_p19)
);

(* dissolve_hierarchy = "yes" *) Macro_MAC_Acc4_top_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U199(
    .din0(pout_temp_32_reg_1659),
    .din1(pout_temp_33_reg_1664),
    .din2(pout_temp_34_reg_1669),
    .din3(pout_temp_35_reg_1674),
    .din4(pout_temp_36_reg_1679),
    .din5(pout_temp_37_reg_1684),
    .din6(pout_temp_38_reg_1689),
    .din7(pout_temp_39_reg_1694),
    .def(tmp_1_fu_1128_p17),
    .sel(trunc_ln235_fu_996_p1),
    .dout(tmp_1_fu_1128_p19)
);

(* dissolve_hierarchy = "yes" *) Macro_MAC_Acc4_top_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U200(
    .din0(pout_temp_40_reg_1699),
    .din1(pout_temp_41_reg_1704),
    .din2(pout_temp_42_reg_1709),
    .din3(pout_temp_43_reg_1714),
    .din4(pout_temp_44_reg_1719),
    .din5(pout_temp_45_reg_1724),
    .din6(pout_temp_46_reg_1729),
    .din7(pout_temp_47_reg_1734),
    .def(tmp_2_fu_1160_p17),
    .sel(trunc_ln235_fu_996_p1),
    .dout(tmp_2_fu_1160_p19)
);

(* dissolve_hierarchy = "yes" *) Macro_MAC_Acc4_top_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U201(
    .din0(pout_temp_48_reg_1739),
    .din1(pout_temp_49_reg_1744),
    .din2(pout_temp_50_reg_1749),
    .din3(pout_temp_51_reg_1754),
    .din4(pout_temp_52_reg_1759),
    .din5(pout_temp_53_reg_1764),
    .din6(pout_temp_54_reg_1769),
    .din7(pout_temp_55_reg_1774),
    .def(tmp_3_fu_1192_p17),
    .sel(trunc_ln235_fu_996_p1),
    .dout(tmp_3_fu_1192_p19)
);

(* dissolve_hierarchy = "yes" *) Macro_MAC_Acc4_top_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U202(
    .din0(pout_temp_56_reg_1779),
    .din1(pout_temp_57_reg_1784),
    .din2(pout_temp_58_reg_1789),
    .din3(pout_temp_59_reg_1794),
    .din4(pout_temp_60_reg_1799),
    .din5(pout_temp_61_reg_1804),
    .din6(pout_temp_62_reg_1809),
    .din7(pout_temp_63_reg_1814),
    .def(tmp_4_fu_1224_p17),
    .sel(trunc_ln235_fu_996_p1),
    .dout(tmp_4_fu_1224_p19)
);

(* dissolve_hierarchy = "yes" *) Macro_MAC_Acc4_top_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U203(
    .din0(pout_local_0_i),
    .din1(pout_local_1_i),
    .din2(pout_local_2_i),
    .din3(pout_local_3_i),
    .din4(pout_local_4_i),
    .din5(pout_local_5_i),
    .din6(pout_local_6_i),
    .din7(pout_local_7_i),
    .def(tmp_5_fu_1261_p17),
    .sel(trunc_ln235_reg_1822_pp0_iter17_reg),
    .dout(tmp_5_fu_1261_p19)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state3) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state3)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end else if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter24 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_mac_sub_fu_360_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_compute_mac_sub_fu_360_ap_start_reg <= 1'b1;
        end else if ((grp_compute_mac_sub_fu_360_ap_ready == 1'b1)) begin
            grp_compute_mac_sub_fu_360_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_mac_sub_fu_400_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_compute_mac_sub_fu_400_ap_start_reg <= 1'b1;
        end else if ((grp_compute_mac_sub_fu_400_ap_ready == 1'b1)) begin
            grp_compute_mac_sub_fu_400_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_mac_sub_fu_440_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_compute_mac_sub_fu_440_ap_start_reg <= 1'b1;
        end else if ((grp_compute_mac_sub_fu_440_ap_ready == 1'b1)) begin
            grp_compute_mac_sub_fu_440_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_mac_sub_fu_480_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_compute_mac_sub_fu_480_ap_start_reg <= 1'b1;
        end else if ((grp_compute_mac_sub_fu_480_ap_ready == 1'b1)) begin
            grp_compute_mac_sub_fu_480_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_mac_sub_fu_520_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_compute_mac_sub_fu_520_ap_start_reg <= 1'b1;
        end else if ((grp_compute_mac_sub_fu_520_ap_ready == 1'b1)) begin
            grp_compute_mac_sub_fu_520_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_mac_sub_fu_560_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_compute_mac_sub_fu_560_ap_start_reg <= 1'b1;
        end else if ((grp_compute_mac_sub_fu_560_ap_ready == 1'b1)) begin
            grp_compute_mac_sub_fu_560_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_mac_sub_fu_600_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_compute_mac_sub_fu_600_ap_start_reg <= 1'b1;
        end else if ((grp_compute_mac_sub_fu_600_ap_ready == 1'b1)) begin
            grp_compute_mac_sub_fu_600_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_mac_sub_fu_640_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_compute_mac_sub_fu_640_ap_start_reg <= 1'b1;
        end else if ((grp_compute_mac_sub_fu_640_ap_ready == 1'b1)) begin
            grp_compute_mac_sub_fu_640_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        j_fu_156 <= 4'd0;
    end else if (((icmp_ln235_fu_984_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        j_fu_156 <= add_ln235_fu_990_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add1_reg_1872 <= grp_fu_684_p2;
        add2_reg_1877 <= grp_fu_688_p2;
        add3_reg_1882 <= grp_fu_692_p2;
        add4_reg_1887 <= grp_fu_696_p2;
        add5_reg_1892 <= grp_fu_700_p2;
        add_reg_1867 <= grp_fu_680_p2;
        final_sum_reg_1897 <= grp_fu_704_p2;
        tmp_5_reg_1902 <= tmp_5_fu_1261_p19;
        trunc_ln235_reg_1822_pp0_iter10_reg <= trunc_ln235_reg_1822_pp0_iter9_reg;
        trunc_ln235_reg_1822_pp0_iter11_reg <= trunc_ln235_reg_1822_pp0_iter10_reg;
        trunc_ln235_reg_1822_pp0_iter12_reg <= trunc_ln235_reg_1822_pp0_iter11_reg;
        trunc_ln235_reg_1822_pp0_iter13_reg <= trunc_ln235_reg_1822_pp0_iter12_reg;
        trunc_ln235_reg_1822_pp0_iter14_reg <= trunc_ln235_reg_1822_pp0_iter13_reg;
        trunc_ln235_reg_1822_pp0_iter15_reg <= trunc_ln235_reg_1822_pp0_iter14_reg;
        trunc_ln235_reg_1822_pp0_iter16_reg <= trunc_ln235_reg_1822_pp0_iter15_reg;
        trunc_ln235_reg_1822_pp0_iter17_reg <= trunc_ln235_reg_1822_pp0_iter16_reg;
        trunc_ln235_reg_1822_pp0_iter18_reg <= trunc_ln235_reg_1822_pp0_iter17_reg;
        trunc_ln235_reg_1822_pp0_iter19_reg <= trunc_ln235_reg_1822_pp0_iter18_reg;
        trunc_ln235_reg_1822_pp0_iter20_reg <= trunc_ln235_reg_1822_pp0_iter19_reg;
        trunc_ln235_reg_1822_pp0_iter21_reg <= trunc_ln235_reg_1822_pp0_iter20_reg;
        trunc_ln235_reg_1822_pp0_iter22_reg <= trunc_ln235_reg_1822_pp0_iter21_reg;
        trunc_ln235_reg_1822_pp0_iter23_reg <= trunc_ln235_reg_1822_pp0_iter22_reg;
        trunc_ln235_reg_1822_pp0_iter2_reg <= trunc_ln235_reg_1822_pp0_iter1_reg;
        trunc_ln235_reg_1822_pp0_iter3_reg <= trunc_ln235_reg_1822_pp0_iter2_reg;
        trunc_ln235_reg_1822_pp0_iter4_reg <= trunc_ln235_reg_1822_pp0_iter3_reg;
        trunc_ln235_reg_1822_pp0_iter5_reg <= trunc_ln235_reg_1822_pp0_iter4_reg;
        trunc_ln235_reg_1822_pp0_iter6_reg <= trunc_ln235_reg_1822_pp0_iter5_reg;
        trunc_ln235_reg_1822_pp0_iter7_reg <= trunc_ln235_reg_1822_pp0_iter6_reg;
        trunc_ln235_reg_1822_pp0_iter8_reg <= trunc_ln235_reg_1822_pp0_iter7_reg;
        trunc_ln235_reg_1822_pp0_iter9_reg <= trunc_ln235_reg_1822_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        pout_temp_10_reg_1549 <= grp_compute_mac_sub_fu_400_ap_return_2;
        pout_temp_11_reg_1554 <= grp_compute_mac_sub_fu_400_ap_return_3;
        pout_temp_12_reg_1559 <= grp_compute_mac_sub_fu_400_ap_return_4;
        pout_temp_13_reg_1564 <= grp_compute_mac_sub_fu_400_ap_return_5;
        pout_temp_14_reg_1569 <= grp_compute_mac_sub_fu_400_ap_return_6;
        pout_temp_15_reg_1574 <= grp_compute_mac_sub_fu_400_ap_return_7;
        pout_temp_16_reg_1579 <= grp_compute_mac_sub_fu_440_ap_return_0;
        pout_temp_17_reg_1584 <= grp_compute_mac_sub_fu_440_ap_return_1;
        pout_temp_18_reg_1589 <= grp_compute_mac_sub_fu_440_ap_return_2;
        pout_temp_19_reg_1594 <= grp_compute_mac_sub_fu_440_ap_return_3;
        pout_temp_1_reg_1504 <= grp_compute_mac_sub_fu_360_ap_return_1;
        pout_temp_20_reg_1599 <= grp_compute_mac_sub_fu_440_ap_return_4;
        pout_temp_21_reg_1604 <= grp_compute_mac_sub_fu_440_ap_return_5;
        pout_temp_22_reg_1609 <= grp_compute_mac_sub_fu_440_ap_return_6;
        pout_temp_23_reg_1614 <= grp_compute_mac_sub_fu_440_ap_return_7;
        pout_temp_24_reg_1619 <= grp_compute_mac_sub_fu_480_ap_return_0;
        pout_temp_25_reg_1624 <= grp_compute_mac_sub_fu_480_ap_return_1;
        pout_temp_26_reg_1629 <= grp_compute_mac_sub_fu_480_ap_return_2;
        pout_temp_27_reg_1634 <= grp_compute_mac_sub_fu_480_ap_return_3;
        pout_temp_28_reg_1639 <= grp_compute_mac_sub_fu_480_ap_return_4;
        pout_temp_29_reg_1644 <= grp_compute_mac_sub_fu_480_ap_return_5;
        pout_temp_2_reg_1509 <= grp_compute_mac_sub_fu_360_ap_return_2;
        pout_temp_30_reg_1649 <= grp_compute_mac_sub_fu_480_ap_return_6;
        pout_temp_31_reg_1654 <= grp_compute_mac_sub_fu_480_ap_return_7;
        pout_temp_32_reg_1659 <= grp_compute_mac_sub_fu_520_ap_return_0;
        pout_temp_33_reg_1664 <= grp_compute_mac_sub_fu_520_ap_return_1;
        pout_temp_34_reg_1669 <= grp_compute_mac_sub_fu_520_ap_return_2;
        pout_temp_35_reg_1674 <= grp_compute_mac_sub_fu_520_ap_return_3;
        pout_temp_36_reg_1679 <= grp_compute_mac_sub_fu_520_ap_return_4;
        pout_temp_37_reg_1684 <= grp_compute_mac_sub_fu_520_ap_return_5;
        pout_temp_38_reg_1689 <= grp_compute_mac_sub_fu_520_ap_return_6;
        pout_temp_39_reg_1694 <= grp_compute_mac_sub_fu_520_ap_return_7;
        pout_temp_3_reg_1514 <= grp_compute_mac_sub_fu_360_ap_return_3;
        pout_temp_40_reg_1699 <= grp_compute_mac_sub_fu_560_ap_return_0;
        pout_temp_41_reg_1704 <= grp_compute_mac_sub_fu_560_ap_return_1;
        pout_temp_42_reg_1709 <= grp_compute_mac_sub_fu_560_ap_return_2;
        pout_temp_43_reg_1714 <= grp_compute_mac_sub_fu_560_ap_return_3;
        pout_temp_44_reg_1719 <= grp_compute_mac_sub_fu_560_ap_return_4;
        pout_temp_45_reg_1724 <= grp_compute_mac_sub_fu_560_ap_return_5;
        pout_temp_46_reg_1729 <= grp_compute_mac_sub_fu_560_ap_return_6;
        pout_temp_47_reg_1734 <= grp_compute_mac_sub_fu_560_ap_return_7;
        pout_temp_48_reg_1739 <= grp_compute_mac_sub_fu_600_ap_return_0;
        pout_temp_49_reg_1744 <= grp_compute_mac_sub_fu_600_ap_return_1;
        pout_temp_4_reg_1519 <= grp_compute_mac_sub_fu_360_ap_return_4;
        pout_temp_50_reg_1749 <= grp_compute_mac_sub_fu_600_ap_return_2;
        pout_temp_51_reg_1754 <= grp_compute_mac_sub_fu_600_ap_return_3;
        pout_temp_52_reg_1759 <= grp_compute_mac_sub_fu_600_ap_return_4;
        pout_temp_53_reg_1764 <= grp_compute_mac_sub_fu_600_ap_return_5;
        pout_temp_54_reg_1769 <= grp_compute_mac_sub_fu_600_ap_return_6;
        pout_temp_55_reg_1774 <= grp_compute_mac_sub_fu_600_ap_return_7;
        pout_temp_56_reg_1779 <= grp_compute_mac_sub_fu_640_ap_return_0;
        pout_temp_57_reg_1784 <= grp_compute_mac_sub_fu_640_ap_return_1;
        pout_temp_58_reg_1789 <= grp_compute_mac_sub_fu_640_ap_return_2;
        pout_temp_59_reg_1794 <= grp_compute_mac_sub_fu_640_ap_return_3;
        pout_temp_5_reg_1524 <= grp_compute_mac_sub_fu_360_ap_return_5;
        pout_temp_60_reg_1799 <= grp_compute_mac_sub_fu_640_ap_return_4;
        pout_temp_61_reg_1804 <= grp_compute_mac_sub_fu_640_ap_return_5;
        pout_temp_62_reg_1809 <= grp_compute_mac_sub_fu_640_ap_return_6;
        pout_temp_63_reg_1814 <= grp_compute_mac_sub_fu_640_ap_return_7;
        pout_temp_6_reg_1529 <= grp_compute_mac_sub_fu_360_ap_return_6;
        pout_temp_7_reg_1534 <= grp_compute_mac_sub_fu_360_ap_return_7;
        pout_temp_8_reg_1539 <= grp_compute_mac_sub_fu_400_ap_return_0;
        pout_temp_9_reg_1544 <= grp_compute_mac_sub_fu_400_ap_return_1;
        pout_temp_reg_1499 <= grp_compute_mac_sub_fu_360_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_1_reg_1847 <= tmp_1_fu_1128_p19;
        tmp_2_reg_1852 <= tmp_2_fu_1160_p19;
        tmp_3_reg_1857 <= tmp_3_fu_1192_p19;
        tmp_4_reg_1862 <= tmp_4_fu_1224_p19;
        tmp_8_reg_1832 <= tmp_8_fu_1032_p19;
        tmp_9_reg_1837 <= tmp_9_fu_1064_p19;
        tmp_reg_1827 <= tmp_fu_1000_p19;
        tmp_s_reg_1842 <= tmp_s_fu_1096_p19;
        trunc_ln235_reg_1822 <= trunc_ln235_fu_996_p1;
        trunc_ln235_reg_1822_pp0_iter1_reg <= trunc_ln235_reg_1822;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state28_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln235_fu_984_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (trunc_ln235_reg_1822_pp0_iter23_reg == 3'd0) & (1'b0 == ap_block_pp0_stage0_01001))) begin
        pout_local_0_o = grp_fu_708_p2;
    end else begin
        pout_local_0_o = pout_local_0_i;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (trunc_ln235_reg_1822_pp0_iter23_reg == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pout_local_0_o_ap_vld = 1'b1;
    end else begin
        pout_local_0_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (trunc_ln235_reg_1822_pp0_iter23_reg == 3'd1) & (1'b0 == ap_block_pp0_stage0_01001))) begin
        pout_local_1_o = grp_fu_708_p2;
    end else begin
        pout_local_1_o = pout_local_1_i;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (trunc_ln235_reg_1822_pp0_iter23_reg == 3'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pout_local_1_o_ap_vld = 1'b1;
    end else begin
        pout_local_1_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (trunc_ln235_reg_1822_pp0_iter23_reg == 3'd2) & (1'b0 == ap_block_pp0_stage0_01001))) begin
        pout_local_2_o = grp_fu_708_p2;
    end else begin
        pout_local_2_o = pout_local_2_i;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (trunc_ln235_reg_1822_pp0_iter23_reg == 3'd2) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pout_local_2_o_ap_vld = 1'b1;
    end else begin
        pout_local_2_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (trunc_ln235_reg_1822_pp0_iter23_reg == 3'd3) & (1'b0 == ap_block_pp0_stage0_01001))) begin
        pout_local_3_o = grp_fu_708_p2;
    end else begin
        pout_local_3_o = pout_local_3_i;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (trunc_ln235_reg_1822_pp0_iter23_reg == 3'd3) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pout_local_3_o_ap_vld = 1'b1;
    end else begin
        pout_local_3_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (trunc_ln235_reg_1822_pp0_iter23_reg == 3'd4) & (1'b0 == ap_block_pp0_stage0_01001))) begin
        pout_local_4_o = grp_fu_708_p2;
    end else begin
        pout_local_4_o = pout_local_4_i;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (trunc_ln235_reg_1822_pp0_iter23_reg == 3'd4) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pout_local_4_o_ap_vld = 1'b1;
    end else begin
        pout_local_4_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (trunc_ln235_reg_1822_pp0_iter23_reg == 3'd5) & (1'b0 == ap_block_pp0_stage0_01001))) begin
        pout_local_5_o = grp_fu_708_p2;
    end else begin
        pout_local_5_o = pout_local_5_i;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (trunc_ln235_reg_1822_pp0_iter23_reg == 3'd5) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pout_local_5_o_ap_vld = 1'b1;
    end else begin
        pout_local_5_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (trunc_ln235_reg_1822_pp0_iter23_reg == 3'd6) & (1'b0 == ap_block_pp0_stage0_01001))) begin
        pout_local_6_o = grp_fu_708_p2;
    end else begin
        pout_local_6_o = pout_local_6_i;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (trunc_ln235_reg_1822_pp0_iter23_reg == 3'd6) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pout_local_6_o_ap_vld = 1'b1;
    end else begin
        pout_local_6_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (trunc_ln235_reg_1822_pp0_iter23_reg == 3'd7) & (1'b0 == ap_block_pp0_stage0_01001))) begin
        pout_local_7_o = grp_fu_708_p2;
    end else begin
        pout_local_7_o = pout_local_7_i;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (trunc_ln235_reg_1822_pp0_iter23_reg == 3'd7) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pout_local_7_o_ap_vld = 1'b1;
    end else begin
        pout_local_7_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (icmp_ln235_fu_984_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone)) & ~((ap_enable_reg_pp0_iter24 == 1'b1) & (ap_enable_reg_pp0_iter23 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter24 == 1'b1) & (ap_enable_reg_pp0_iter23 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)) | ((ap_enable_reg_pp0_iter1 == 1'b0) & (icmp_ln235_fu_984_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln235_fu_990_p2 = (j_fu_156 + 4'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_compute_mac_sub_fu_640_ap_done == 1'b0) | (grp_compute_mac_sub_fu_600_ap_done == 1'b0) | (grp_compute_mac_sub_fu_560_ap_done == 1'b0) | (grp_compute_mac_sub_fu_520_ap_done == 1'b0) | (grp_compute_mac_sub_fu_480_ap_done == 1'b0) | (grp_compute_mac_sub_fu_440_ap_done == 1'b0) | (grp_compute_mac_sub_fu_400_ap_done == 1'b0) | (grp_compute_mac_sub_fu_360_ap_done == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign grp_compute_mac_sub_fu_360_ap_start = grp_compute_mac_sub_fu_360_ap_start_reg;

assign grp_compute_mac_sub_fu_400_ap_start = grp_compute_mac_sub_fu_400_ap_start_reg;

assign grp_compute_mac_sub_fu_440_ap_start = grp_compute_mac_sub_fu_440_ap_start_reg;

assign grp_compute_mac_sub_fu_480_ap_start = grp_compute_mac_sub_fu_480_ap_start_reg;

assign grp_compute_mac_sub_fu_520_ap_start = grp_compute_mac_sub_fu_520_ap_start_reg;

assign grp_compute_mac_sub_fu_560_ap_start = grp_compute_mac_sub_fu_560_ap_start_reg;

assign grp_compute_mac_sub_fu_600_ap_start = grp_compute_mac_sub_fu_600_ap_start_reg;

assign grp_compute_mac_sub_fu_640_ap_start = grp_compute_mac_sub_fu_640_ap_start_reg;

assign icmp_ln235_fu_984_p2 = ((j_fu_156 == 4'd8) ? 1'b1 : 1'b0);

assign mro_s_0_010_read = grp_compute_mac_sub_fu_480_mro_s_0_read;

assign mro_s_0_011_read = grp_compute_mac_sub_fu_520_mro_s_0_read;

assign mro_s_0_012_read = grp_compute_mac_sub_fu_560_mro_s_0_read;

assign mro_s_0_013_read = grp_compute_mac_sub_fu_600_mro_s_0_read;

assign mro_s_0_014_read = grp_compute_mac_sub_fu_640_mro_s_0_read;

assign mro_s_0_08_read = grp_compute_mac_sub_fu_400_mro_s_0_read;

assign mro_s_0_09_read = grp_compute_mac_sub_fu_440_mro_s_0_read;

assign mro_s_0_0_read = grp_compute_mac_sub_fu_360_mro_s_0_read;

assign tmp_1_fu_1128_p17 = 'bx;

assign tmp_2_fu_1160_p17 = 'bx;

assign tmp_3_fu_1192_p17 = 'bx;

assign tmp_4_fu_1224_p17 = 'bx;

assign tmp_5_fu_1261_p17 = 'bx;

assign tmp_8_fu_1032_p17 = 'bx;

assign tmp_9_fu_1064_p17 = 'bx;

assign tmp_fu_1000_p17 = 'bx;

assign tmp_s_fu_1096_p17 = 'bx;

assign trunc_ln235_fu_996_p1 = j_fu_156[2:0];

assign xi_s_0_01_read = grp_compute_mac_sub_fu_400_xi_s_0_read;

assign xi_s_0_02_read = grp_compute_mac_sub_fu_440_xi_s_0_read;

assign xi_s_0_03_read = grp_compute_mac_sub_fu_480_xi_s_0_read;

assign xi_s_0_04_read = grp_compute_mac_sub_fu_520_xi_s_0_read;

assign xi_s_0_05_read = grp_compute_mac_sub_fu_560_xi_s_0_read;

assign xi_s_0_06_read = grp_compute_mac_sub_fu_600_xi_s_0_read;

assign xi_s_0_07_read = grp_compute_mac_sub_fu_640_xi_s_0_read;

assign xi_s_0_0_read = grp_compute_mac_sub_fu_360_xi_s_0_read;

endmodule //Macro_MAC_Acc4_top_compute_mac
