# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/adnepukan/aicas4qwen/hardware/project_1/project_1.srcs/sources_1/bd/system/ip/system_Top_0_0/system_Top_0_0.xci
# IP: The module: 'system_Top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/adnepukan/aicas4qwen/hardware/project_1/project_1.srcs/sources_1/ip/blk_mem_gen_asup/blk_mem_gen_asup.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_asup || ORIG_REF_NAME==blk_mem_gen_asup} -quiet] -quiet

# IP: /home/adnepukan/aicas4qwen/hardware/project_1/project_1.srcs/sources_1/ip/blk_mem_gen_psup/blk_mem_gen_psup.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_psup || ORIG_REF_NAME==blk_mem_gen_psup} -quiet] -quiet

# IP: /home/adnepukan/aicas4qwen/hardware/project_1/project_1.srcs/sources_1/ip/blk_mem_gen_temp/blk_mem_gen_temp.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_temp || ORIG_REF_NAME==blk_mem_gen_temp} -quiet] -quiet

# IP: /home/adnepukan/aicas4qwen/hardware/project_1/project_1.srcs/sources_1/ip/dsp_macro_bypass/dsp_macro_bypass.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dsp_macro_bypass || ORIG_REF_NAME==dsp_macro_bypass} -quiet] -quiet

# IP: /home/adnepukan/aicas4qwen/hardware/project_1/project_1.srcs/sources_1/ip/dsp_macro_exp_silu/dsp_macro_exp_silu.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dsp_macro_exp_silu || ORIG_REF_NAME==dsp_macro_exp_silu} -quiet] -quiet

# IP: /home/adnepukan/aicas4qwen/hardware/project_1/project_1.srcs/sources_1/ip/dsp_macro_0/dsp_macro_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dsp_macro_0 || ORIG_REF_NAME==dsp_macro_0} -quiet] -quiet

# IP: /home/adnepukan/aicas4qwen/hardware/project_1/project_1.srcs/sources_1/ip/blk_mem_gen_lnx/blk_mem_gen_lnx.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_lnx || ORIG_REF_NAME==blk_mem_gen_lnx} -quiet] -quiet

# XDC: /home/adnepukan/aicas4qwen/hardware/project_1/project_1.gen/sources_1/bd/system/ip/system_Top_0_0/system_Top_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_Top_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/adnepukan/aicas4qwen/hardware/project_1/project_1.srcs/sources_1/bd/system/ip/system_Top_0_0/system_Top_0_0.xci
# IP: The module: 'system_Top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/adnepukan/aicas4qwen/hardware/project_1/project_1.srcs/sources_1/ip/blk_mem_gen_asup/blk_mem_gen_asup.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_asup || ORIG_REF_NAME==blk_mem_gen_asup} -quiet] -quiet

# IP: /home/adnepukan/aicas4qwen/hardware/project_1/project_1.srcs/sources_1/ip/blk_mem_gen_psup/blk_mem_gen_psup.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_psup || ORIG_REF_NAME==blk_mem_gen_psup} -quiet] -quiet

# IP: /home/adnepukan/aicas4qwen/hardware/project_1/project_1.srcs/sources_1/ip/blk_mem_gen_temp/blk_mem_gen_temp.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_temp || ORIG_REF_NAME==blk_mem_gen_temp} -quiet] -quiet

# IP: /home/adnepukan/aicas4qwen/hardware/project_1/project_1.srcs/sources_1/ip/dsp_macro_bypass/dsp_macro_bypass.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dsp_macro_bypass || ORIG_REF_NAME==dsp_macro_bypass} -quiet] -quiet

# IP: /home/adnepukan/aicas4qwen/hardware/project_1/project_1.srcs/sources_1/ip/dsp_macro_exp_silu/dsp_macro_exp_silu.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dsp_macro_exp_silu || ORIG_REF_NAME==dsp_macro_exp_silu} -quiet] -quiet

# IP: /home/adnepukan/aicas4qwen/hardware/project_1/project_1.srcs/sources_1/ip/dsp_macro_0/dsp_macro_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dsp_macro_0 || ORIG_REF_NAME==dsp_macro_0} -quiet] -quiet

# IP: /home/adnepukan/aicas4qwen/hardware/project_1/project_1.srcs/sources_1/ip/blk_mem_gen_lnx/blk_mem_gen_lnx.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_lnx || ORIG_REF_NAME==blk_mem_gen_lnx} -quiet] -quiet

# XDC: /home/adnepukan/aicas4qwen/hardware/project_1/project_1.gen/sources_1/bd/system/ip/system_Top_0_0/system_Top_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_Top_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
