-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Macro_MAC_Acc4_top_read_xi_to_stream is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    xi0_s_M_elems_V_0_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xi0_s_M_elems_V_0_full_n : IN STD_LOGIC;
    xi0_s_M_elems_V_0_write : OUT STD_LOGIC;
    xi0_s_M_elems_V_4_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xi0_s_M_elems_V_4_full_n : IN STD_LOGIC;
    xi0_s_M_elems_V_4_write : OUT STD_LOGIC;
    xi1_s_M_elems_V_0_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xi1_s_M_elems_V_0_full_n : IN STD_LOGIC;
    xi1_s_M_elems_V_0_write : OUT STD_LOGIC;
    xi1_s_M_elems_V_4_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xi1_s_M_elems_V_4_full_n : IN STD_LOGIC;
    xi1_s_M_elems_V_4_write : OUT STD_LOGIC;
    xi2_s_M_elems_V_0_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xi2_s_M_elems_V_0_full_n : IN STD_LOGIC;
    xi2_s_M_elems_V_0_write : OUT STD_LOGIC;
    xi2_s_M_elems_V_4_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xi2_s_M_elems_V_4_full_n : IN STD_LOGIC;
    xi2_s_M_elems_V_4_write : OUT STD_LOGIC;
    xi3_s_M_elems_V_0_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xi3_s_M_elems_V_0_full_n : IN STD_LOGIC;
    xi3_s_M_elems_V_0_write : OUT STD_LOGIC;
    xi3_s_M_elems_V_4_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xi3_s_M_elems_V_4_full_n : IN STD_LOGIC;
    xi3_s_M_elems_V_4_write : OUT STD_LOGIC;
    xi0_s_M_elems_V_1_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xi0_s_M_elems_V_1_full_n : IN STD_LOGIC;
    xi0_s_M_elems_V_1_write : OUT STD_LOGIC;
    xi0_s_M_elems_V_5_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xi0_s_M_elems_V_5_full_n : IN STD_LOGIC;
    xi0_s_M_elems_V_5_write : OUT STD_LOGIC;
    xi1_s_M_elems_V_1_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xi1_s_M_elems_V_1_full_n : IN STD_LOGIC;
    xi1_s_M_elems_V_1_write : OUT STD_LOGIC;
    xi1_s_M_elems_V_5_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xi1_s_M_elems_V_5_full_n : IN STD_LOGIC;
    xi1_s_M_elems_V_5_write : OUT STD_LOGIC;
    xi2_s_M_elems_V_1_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xi2_s_M_elems_V_1_full_n : IN STD_LOGIC;
    xi2_s_M_elems_V_1_write : OUT STD_LOGIC;
    xi2_s_M_elems_V_5_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xi2_s_M_elems_V_5_full_n : IN STD_LOGIC;
    xi2_s_M_elems_V_5_write : OUT STD_LOGIC;
    xi3_s_M_elems_V_1_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xi3_s_M_elems_V_1_full_n : IN STD_LOGIC;
    xi3_s_M_elems_V_1_write : OUT STD_LOGIC;
    xi3_s_M_elems_V_5_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xi3_s_M_elems_V_5_full_n : IN STD_LOGIC;
    xi3_s_M_elems_V_5_write : OUT STD_LOGIC;
    xi0_s_M_elems_V_2_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xi0_s_M_elems_V_2_full_n : IN STD_LOGIC;
    xi0_s_M_elems_V_2_write : OUT STD_LOGIC;
    xi0_s_M_elems_V_6_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xi0_s_M_elems_V_6_full_n : IN STD_LOGIC;
    xi0_s_M_elems_V_6_write : OUT STD_LOGIC;
    xi1_s_M_elems_V_2_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xi1_s_M_elems_V_2_full_n : IN STD_LOGIC;
    xi1_s_M_elems_V_2_write : OUT STD_LOGIC;
    xi1_s_M_elems_V_6_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xi1_s_M_elems_V_6_full_n : IN STD_LOGIC;
    xi1_s_M_elems_V_6_write : OUT STD_LOGIC;
    xi2_s_M_elems_V_2_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xi2_s_M_elems_V_2_full_n : IN STD_LOGIC;
    xi2_s_M_elems_V_2_write : OUT STD_LOGIC;
    xi2_s_M_elems_V_6_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xi2_s_M_elems_V_6_full_n : IN STD_LOGIC;
    xi2_s_M_elems_V_6_write : OUT STD_LOGIC;
    xi3_s_M_elems_V_2_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xi3_s_M_elems_V_2_full_n : IN STD_LOGIC;
    xi3_s_M_elems_V_2_write : OUT STD_LOGIC;
    xi3_s_M_elems_V_6_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xi3_s_M_elems_V_6_full_n : IN STD_LOGIC;
    xi3_s_M_elems_V_6_write : OUT STD_LOGIC;
    xi0_s_M_elems_V_7_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xi0_s_M_elems_V_7_full_n : IN STD_LOGIC;
    xi0_s_M_elems_V_7_write : OUT STD_LOGIC;
    xi1_s_M_elems_V_7_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xi1_s_M_elems_V_7_full_n : IN STD_LOGIC;
    xi1_s_M_elems_V_7_write : OUT STD_LOGIC;
    xi2_s_M_elems_V_7_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xi2_s_M_elems_V_7_full_n : IN STD_LOGIC;
    xi2_s_M_elems_V_7_write : OUT STD_LOGIC;
    xi3_s_M_elems_V_7_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xi3_s_M_elems_V_7_full_n : IN STD_LOGIC;
    xi3_s_M_elems_V_7_write : OUT STD_LOGIC;
    xi0_s_M_elems_V_3_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xi0_s_M_elems_V_3_full_n : IN STD_LOGIC;
    xi0_s_M_elems_V_3_write : OUT STD_LOGIC;
    xi1_s_M_elems_V_3_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xi1_s_M_elems_V_3_full_n : IN STD_LOGIC;
    xi1_s_M_elems_V_3_write : OUT STD_LOGIC;
    xi2_s_M_elems_V_3_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xi2_s_M_elems_V_3_full_n : IN STD_LOGIC;
    xi2_s_M_elems_V_3_write : OUT STD_LOGIC;
    xi3_s_M_elems_V_3_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xi3_s_M_elems_V_3_full_n : IN STD_LOGIC;
    xi3_s_M_elems_V_3_write : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (127 downto 0) );
end;


architecture behav of Macro_MAC_Acc4_top_read_xi_to_stream is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal trunc_ln121_reg_509 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln122_reg_513 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter1_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln116_fu_416_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal xi3_s_M_elems_V_2_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal xi3_s_M_elems_V_6_blk_n : STD_LOGIC;
    signal xi3_s_M_elems_V_1_blk_n : STD_LOGIC;
    signal xi3_s_M_elems_V_5_blk_n : STD_LOGIC;
    signal xi3_s_M_elems_V_0_blk_n : STD_LOGIC;
    signal xi3_s_M_elems_V_4_blk_n : STD_LOGIC;
    signal xi2_s_M_elems_V_2_blk_n : STD_LOGIC;
    signal xi2_s_M_elems_V_6_blk_n : STD_LOGIC;
    signal xi2_s_M_elems_V_1_blk_n : STD_LOGIC;
    signal xi2_s_M_elems_V_5_blk_n : STD_LOGIC;
    signal xi2_s_M_elems_V_0_blk_n : STD_LOGIC;
    signal xi2_s_M_elems_V_4_blk_n : STD_LOGIC;
    signal xi1_s_M_elems_V_2_blk_n : STD_LOGIC;
    signal xi1_s_M_elems_V_6_blk_n : STD_LOGIC;
    signal xi1_s_M_elems_V_1_blk_n : STD_LOGIC;
    signal xi1_s_M_elems_V_5_blk_n : STD_LOGIC;
    signal xi1_s_M_elems_V_0_blk_n : STD_LOGIC;
    signal xi1_s_M_elems_V_4_blk_n : STD_LOGIC;
    signal xi0_s_M_elems_V_3_blk_n : STD_LOGIC;
    signal xi1_s_M_elems_V_3_blk_n : STD_LOGIC;
    signal xi2_s_M_elems_V_3_blk_n : STD_LOGIC;
    signal xi3_s_M_elems_V_3_blk_n : STD_LOGIC;
    signal xi0_s_M_elems_V_7_blk_n : STD_LOGIC;
    signal xi1_s_M_elems_V_7_blk_n : STD_LOGIC;
    signal xi2_s_M_elems_V_7_blk_n : STD_LOGIC;
    signal xi3_s_M_elems_V_7_blk_n : STD_LOGIC;
    signal xi0_s_M_elems_V_2_blk_n : STD_LOGIC;
    signal xi0_s_M_elems_V_6_blk_n : STD_LOGIC;
    signal xi0_s_M_elems_V_1_blk_n : STD_LOGIC;
    signal xi0_s_M_elems_V_5_blk_n : STD_LOGIC;
    signal xi0_s_M_elems_V_0_blk_n : STD_LOGIC;
    signal xi0_s_M_elems_V_4_blk_n : STD_LOGIC;
    signal bitcast_ln118_fu_362_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln118_reg_458 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal bitcast_ln118_1_fu_376_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln118_1_reg_470 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln118_2_fu_390_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln118_2_reg_482 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln118_3_fu_404_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln118_3_reg_494 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln121_fu_428_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln122_fu_440_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_fu_124 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln116_fu_422_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal empty_fu_358_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_0_0_1_partselect_i_fu_366_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_0_0_2_partselect_i_fu_380_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_0_0_3_partselect_i_fu_394_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln_fu_432_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component Macro_MAC_Acc4_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component Macro_MAC_Acc4_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    i_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln116_fu_416_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_124 <= add_ln116_fu_422_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_124 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                bitcast_ln118_1_reg_470 <= bitcast_ln118_1_fu_376_p1;
                bitcast_ln118_2_reg_482 <= bitcast_ln118_2_fu_390_p1;
                bitcast_ln118_3_reg_494 <= bitcast_ln118_3_fu_404_p1;
                bitcast_ln118_reg_458 <= bitcast_ln118_fu_362_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln122_reg_513 <= icmp_ln122_fu_440_p2;
                trunc_ln121_reg_509 <= trunc_ln121_fu_428_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln116_fu_422_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv5_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_01001_grp1 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1));
    end process;


    ap_block_state2_pp0_stage0_iter1_grp1_assign_proc : process(xi0_s_M_elems_V_0_full_n, xi0_s_M_elems_V_4_full_n, xi1_s_M_elems_V_0_full_n, xi1_s_M_elems_V_4_full_n, xi2_s_M_elems_V_0_full_n, xi2_s_M_elems_V_4_full_n, xi3_s_M_elems_V_0_full_n, xi3_s_M_elems_V_4_full_n, xi0_s_M_elems_V_1_full_n, xi0_s_M_elems_V_5_full_n, xi1_s_M_elems_V_1_full_n, xi1_s_M_elems_V_5_full_n, xi2_s_M_elems_V_1_full_n, xi2_s_M_elems_V_5_full_n, xi3_s_M_elems_V_1_full_n, xi3_s_M_elems_V_5_full_n, xi0_s_M_elems_V_2_full_n, xi0_s_M_elems_V_6_full_n, xi1_s_M_elems_V_2_full_n, xi1_s_M_elems_V_6_full_n, xi2_s_M_elems_V_2_full_n, xi2_s_M_elems_V_6_full_n, xi3_s_M_elems_V_2_full_n, xi3_s_M_elems_V_6_full_n, xi0_s_M_elems_V_7_full_n, xi1_s_M_elems_V_7_full_n, xi2_s_M_elems_V_7_full_n, xi3_s_M_elems_V_7_full_n, xi0_s_M_elems_V_3_full_n, xi1_s_M_elems_V_3_full_n, xi2_s_M_elems_V_3_full_n, xi3_s_M_elems_V_3_full_n, trunc_ln121_reg_509, icmp_ln122_reg_513)
    begin
                ap_block_state2_pp0_stage0_iter1_grp1 <= (((icmp_ln122_reg_513 = ap_const_lv1_1) and (xi3_s_M_elems_V_3_full_n = ap_const_logic_0)) or ((icmp_ln122_reg_513 = ap_const_lv1_1) and (xi2_s_M_elems_V_3_full_n = ap_const_logic_0)) or ((icmp_ln122_reg_513 = ap_const_lv1_1) and (xi1_s_M_elems_V_3_full_n = ap_const_logic_0)) or ((icmp_ln122_reg_513 = ap_const_lv1_1) and (xi0_s_M_elems_V_3_full_n = ap_const_logic_0)) or ((icmp_ln122_reg_513 = ap_const_lv1_0) and (xi3_s_M_elems_V_7_full_n = ap_const_logic_0)) or ((icmp_ln122_reg_513 = ap_const_lv1_0) and (xi2_s_M_elems_V_7_full_n = ap_const_logic_0)) or ((icmp_ln122_reg_513 = ap_const_lv1_0) and (xi1_s_M_elems_V_7_full_n = ap_const_logic_0)) or ((icmp_ln122_reg_513 = ap_const_lv1_0) and (xi0_s_M_elems_V_7_full_n = ap_const_logic_0)) or ((xi0_s_M_elems_V_6_full_n = ap_const_logic_0) and (trunc_ln121_reg_509 = ap_const_lv1_1)) or ((xi0_s_M_elems_V_2_full_n = ap_const_logic_0) and (trunc_ln121_reg_509 = ap_const_lv1_0)) or ((xi3_s_M_elems_V_5_full_n = ap_const_logic_0) and (trunc_ln121_reg_509 = ap_const_lv1_1)) or 
    ((xi3_s_M_elems_V_1_full_n = ap_const_logic_0) and (trunc_ln121_reg_509 = ap_const_lv1_0)) or ((xi2_s_M_elems_V_5_full_n = ap_const_logic_0) and (trunc_ln121_reg_509 = ap_const_lv1_1)) or ((xi2_s_M_elems_V_1_full_n = ap_const_logic_0) and (trunc_ln121_reg_509 = ap_const_lv1_0)) or ((xi1_s_M_elems_V_5_full_n = ap_const_logic_0) and (trunc_ln121_reg_509 = ap_const_lv1_1)) or ((xi1_s_M_elems_V_1_full_n = ap_const_logic_0) and (trunc_ln121_reg_509 = ap_const_lv1_0)) or ((xi0_s_M_elems_V_5_full_n = ap_const_logic_0) and (trunc_ln121_reg_509 = ap_const_lv1_1)) or ((xi0_s_M_elems_V_1_full_n = ap_const_logic_0) and (trunc_ln121_reg_509 = ap_const_lv1_0)) or ((xi3_s_M_elems_V_4_full_n = ap_const_logic_0) and (trunc_ln121_reg_509 = ap_const_lv1_1)) or ((xi3_s_M_elems_V_0_full_n = ap_const_logic_0) and (trunc_ln121_reg_509 = ap_const_lv1_0)) or ((xi2_s_M_elems_V_4_full_n = ap_const_logic_0) and (trunc_ln121_reg_509 = ap_const_lv1_1)) or ((xi2_s_M_elems_V_0_full_n = ap_const_logic_0) and (trunc_ln121_reg_509 = ap_const_lv1_0)) 
    or ((xi1_s_M_elems_V_4_full_n = ap_const_logic_0) and (trunc_ln121_reg_509 = ap_const_lv1_1)) or ((xi1_s_M_elems_V_0_full_n = ap_const_logic_0) and (trunc_ln121_reg_509 = ap_const_lv1_0)) or ((trunc_ln121_reg_509 = ap_const_lv1_1) and (xi3_s_M_elems_V_6_full_n = ap_const_logic_0)) or ((trunc_ln121_reg_509 = ap_const_lv1_1) and (xi2_s_M_elems_V_6_full_n = ap_const_logic_0)) or ((trunc_ln121_reg_509 = ap_const_lv1_1) and (xi1_s_M_elems_V_6_full_n = ap_const_logic_0)) or ((xi0_s_M_elems_V_4_full_n = ap_const_logic_0) and (trunc_ln121_reg_509 = ap_const_lv1_1)) or ((trunc_ln121_reg_509 = ap_const_lv1_0) and (xi3_s_M_elems_V_2_full_n = ap_const_logic_0)) or ((trunc_ln121_reg_509 = ap_const_lv1_0) and (xi2_s_M_elems_V_2_full_n = ap_const_logic_0)) or ((trunc_ln121_reg_509 = ap_const_lv1_0) and (xi1_s_M_elems_V_2_full_n = ap_const_logic_0)) or ((xi0_s_M_elems_V_0_full_n = ap_const_logic_0) and (trunc_ln121_reg_509 = ap_const_lv1_0)));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln116_fu_416_p2)
    begin
        if (((icmp_ln116_fu_416_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, i_fu_124, ap_loop_init, ap_block_pp0_stage0)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_124;
        end if; 
    end process;

    bitcast_ln118_1_fu_376_p1 <= p_0_0_1_partselect_i_fu_366_p4;
    bitcast_ln118_2_fu_390_p1 <= p_0_0_2_partselect_i_fu_380_p4;
    bitcast_ln118_3_fu_404_p1 <= p_0_0_3_partselect_i_fu_394_p4;
    bitcast_ln118_fu_362_p1 <= empty_fu_358_p1;
    empty_fu_358_p1 <= p_read(32 - 1 downto 0);
    icmp_ln116_fu_416_p2 <= "1" when (ap_sig_allocacmp_i_1 = ap_const_lv5_10) else "0";
    icmp_ln122_fu_440_p2 <= "1" when (or_ln_fu_432_p3 = ap_const_lv3_3) else "0";
    or_ln_fu_432_p3 <= (trunc_ln121_fu_428_p1 & ap_const_lv2_3);
    p_0_0_1_partselect_i_fu_366_p4 <= p_read(63 downto 32);
    p_0_0_2_partselect_i_fu_380_p4 <= p_read(95 downto 64);
    p_0_0_3_partselect_i_fu_394_p4 <= p_read(127 downto 96);
    trunc_ln121_fu_428_p1 <= ap_sig_allocacmp_i_1(1 - 1 downto 0);

    xi0_s_M_elems_V_0_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xi0_s_M_elems_V_0_full_n, trunc_ln121_reg_509, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_0))) then 
            xi0_s_M_elems_V_0_blk_n <= xi0_s_M_elems_V_0_full_n;
        else 
            xi0_s_M_elems_V_0_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xi0_s_M_elems_V_0_din <= bitcast_ln118_reg_458;

    xi0_s_M_elems_V_0_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln121_reg_509, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_0))) then 
            xi0_s_M_elems_V_0_write <= ap_const_logic_1;
        else 
            xi0_s_M_elems_V_0_write <= ap_const_logic_0;
        end if; 
    end process;


    xi0_s_M_elems_V_1_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xi0_s_M_elems_V_1_full_n, trunc_ln121_reg_509, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_0))) then 
            xi0_s_M_elems_V_1_blk_n <= xi0_s_M_elems_V_1_full_n;
        else 
            xi0_s_M_elems_V_1_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xi0_s_M_elems_V_1_din <= bitcast_ln118_1_reg_470;

    xi0_s_M_elems_V_1_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln121_reg_509, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_0))) then 
            xi0_s_M_elems_V_1_write <= ap_const_logic_1;
        else 
            xi0_s_M_elems_V_1_write <= ap_const_logic_0;
        end if; 
    end process;


    xi0_s_M_elems_V_2_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xi0_s_M_elems_V_2_full_n, trunc_ln121_reg_509, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_0))) then 
            xi0_s_M_elems_V_2_blk_n <= xi0_s_M_elems_V_2_full_n;
        else 
            xi0_s_M_elems_V_2_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xi0_s_M_elems_V_2_din <= bitcast_ln118_2_reg_482;

    xi0_s_M_elems_V_2_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln121_reg_509, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_0))) then 
            xi0_s_M_elems_V_2_write <= ap_const_logic_1;
        else 
            xi0_s_M_elems_V_2_write <= ap_const_logic_0;
        end if; 
    end process;


    xi0_s_M_elems_V_3_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xi0_s_M_elems_V_3_full_n, icmp_ln122_reg_513, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (icmp_ln122_reg_513 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xi0_s_M_elems_V_3_blk_n <= xi0_s_M_elems_V_3_full_n;
        else 
            xi0_s_M_elems_V_3_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xi0_s_M_elems_V_3_din <= bitcast_ln118_3_reg_494;

    xi0_s_M_elems_V_3_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln122_reg_513, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (icmp_ln122_reg_513 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xi0_s_M_elems_V_3_write <= ap_const_logic_1;
        else 
            xi0_s_M_elems_V_3_write <= ap_const_logic_0;
        end if; 
    end process;


    xi0_s_M_elems_V_4_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xi0_s_M_elems_V_4_full_n, trunc_ln121_reg_509, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_1))) then 
            xi0_s_M_elems_V_4_blk_n <= xi0_s_M_elems_V_4_full_n;
        else 
            xi0_s_M_elems_V_4_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xi0_s_M_elems_V_4_din <= bitcast_ln118_reg_458;

    xi0_s_M_elems_V_4_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln121_reg_509, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_1))) then 
            xi0_s_M_elems_V_4_write <= ap_const_logic_1;
        else 
            xi0_s_M_elems_V_4_write <= ap_const_logic_0;
        end if; 
    end process;


    xi0_s_M_elems_V_5_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xi0_s_M_elems_V_5_full_n, trunc_ln121_reg_509, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_1))) then 
            xi0_s_M_elems_V_5_blk_n <= xi0_s_M_elems_V_5_full_n;
        else 
            xi0_s_M_elems_V_5_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xi0_s_M_elems_V_5_din <= bitcast_ln118_1_reg_470;

    xi0_s_M_elems_V_5_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln121_reg_509, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_1))) then 
            xi0_s_M_elems_V_5_write <= ap_const_logic_1;
        else 
            xi0_s_M_elems_V_5_write <= ap_const_logic_0;
        end if; 
    end process;


    xi0_s_M_elems_V_6_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xi0_s_M_elems_V_6_full_n, trunc_ln121_reg_509, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_1))) then 
            xi0_s_M_elems_V_6_blk_n <= xi0_s_M_elems_V_6_full_n;
        else 
            xi0_s_M_elems_V_6_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xi0_s_M_elems_V_6_din <= bitcast_ln118_2_reg_482;

    xi0_s_M_elems_V_6_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln121_reg_509, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_1))) then 
            xi0_s_M_elems_V_6_write <= ap_const_logic_1;
        else 
            xi0_s_M_elems_V_6_write <= ap_const_logic_0;
        end if; 
    end process;


    xi0_s_M_elems_V_7_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xi0_s_M_elems_V_7_full_n, icmp_ln122_reg_513, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (icmp_ln122_reg_513 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xi0_s_M_elems_V_7_blk_n <= xi0_s_M_elems_V_7_full_n;
        else 
            xi0_s_M_elems_V_7_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xi0_s_M_elems_V_7_din <= bitcast_ln118_3_reg_494;

    xi0_s_M_elems_V_7_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln122_reg_513, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (icmp_ln122_reg_513 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xi0_s_M_elems_V_7_write <= ap_const_logic_1;
        else 
            xi0_s_M_elems_V_7_write <= ap_const_logic_0;
        end if; 
    end process;


    xi1_s_M_elems_V_0_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xi1_s_M_elems_V_0_full_n, trunc_ln121_reg_509, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_0))) then 
            xi1_s_M_elems_V_0_blk_n <= xi1_s_M_elems_V_0_full_n;
        else 
            xi1_s_M_elems_V_0_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xi1_s_M_elems_V_0_din <= bitcast_ln118_reg_458;

    xi1_s_M_elems_V_0_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln121_reg_509, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_0))) then 
            xi1_s_M_elems_V_0_write <= ap_const_logic_1;
        else 
            xi1_s_M_elems_V_0_write <= ap_const_logic_0;
        end if; 
    end process;


    xi1_s_M_elems_V_1_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xi1_s_M_elems_V_1_full_n, trunc_ln121_reg_509, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_0))) then 
            xi1_s_M_elems_V_1_blk_n <= xi1_s_M_elems_V_1_full_n;
        else 
            xi1_s_M_elems_V_1_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xi1_s_M_elems_V_1_din <= bitcast_ln118_1_reg_470;

    xi1_s_M_elems_V_1_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln121_reg_509, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_0))) then 
            xi1_s_M_elems_V_1_write <= ap_const_logic_1;
        else 
            xi1_s_M_elems_V_1_write <= ap_const_logic_0;
        end if; 
    end process;


    xi1_s_M_elems_V_2_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xi1_s_M_elems_V_2_full_n, trunc_ln121_reg_509, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_0))) then 
            xi1_s_M_elems_V_2_blk_n <= xi1_s_M_elems_V_2_full_n;
        else 
            xi1_s_M_elems_V_2_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xi1_s_M_elems_V_2_din <= bitcast_ln118_2_reg_482;

    xi1_s_M_elems_V_2_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln121_reg_509, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_0))) then 
            xi1_s_M_elems_V_2_write <= ap_const_logic_1;
        else 
            xi1_s_M_elems_V_2_write <= ap_const_logic_0;
        end if; 
    end process;


    xi1_s_M_elems_V_3_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xi1_s_M_elems_V_3_full_n, icmp_ln122_reg_513, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (icmp_ln122_reg_513 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xi1_s_M_elems_V_3_blk_n <= xi1_s_M_elems_V_3_full_n;
        else 
            xi1_s_M_elems_V_3_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xi1_s_M_elems_V_3_din <= bitcast_ln118_3_reg_494;

    xi1_s_M_elems_V_3_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln122_reg_513, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (icmp_ln122_reg_513 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xi1_s_M_elems_V_3_write <= ap_const_logic_1;
        else 
            xi1_s_M_elems_V_3_write <= ap_const_logic_0;
        end if; 
    end process;


    xi1_s_M_elems_V_4_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xi1_s_M_elems_V_4_full_n, trunc_ln121_reg_509, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_1))) then 
            xi1_s_M_elems_V_4_blk_n <= xi1_s_M_elems_V_4_full_n;
        else 
            xi1_s_M_elems_V_4_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xi1_s_M_elems_V_4_din <= bitcast_ln118_reg_458;

    xi1_s_M_elems_V_4_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln121_reg_509, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_1))) then 
            xi1_s_M_elems_V_4_write <= ap_const_logic_1;
        else 
            xi1_s_M_elems_V_4_write <= ap_const_logic_0;
        end if; 
    end process;


    xi1_s_M_elems_V_5_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xi1_s_M_elems_V_5_full_n, trunc_ln121_reg_509, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_1))) then 
            xi1_s_M_elems_V_5_blk_n <= xi1_s_M_elems_V_5_full_n;
        else 
            xi1_s_M_elems_V_5_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xi1_s_M_elems_V_5_din <= bitcast_ln118_1_reg_470;

    xi1_s_M_elems_V_5_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln121_reg_509, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_1))) then 
            xi1_s_M_elems_V_5_write <= ap_const_logic_1;
        else 
            xi1_s_M_elems_V_5_write <= ap_const_logic_0;
        end if; 
    end process;


    xi1_s_M_elems_V_6_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xi1_s_M_elems_V_6_full_n, trunc_ln121_reg_509, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_1))) then 
            xi1_s_M_elems_V_6_blk_n <= xi1_s_M_elems_V_6_full_n;
        else 
            xi1_s_M_elems_V_6_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xi1_s_M_elems_V_6_din <= bitcast_ln118_2_reg_482;

    xi1_s_M_elems_V_6_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln121_reg_509, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_1))) then 
            xi1_s_M_elems_V_6_write <= ap_const_logic_1;
        else 
            xi1_s_M_elems_V_6_write <= ap_const_logic_0;
        end if; 
    end process;


    xi1_s_M_elems_V_7_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xi1_s_M_elems_V_7_full_n, icmp_ln122_reg_513, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (icmp_ln122_reg_513 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xi1_s_M_elems_V_7_blk_n <= xi1_s_M_elems_V_7_full_n;
        else 
            xi1_s_M_elems_V_7_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xi1_s_M_elems_V_7_din <= bitcast_ln118_3_reg_494;

    xi1_s_M_elems_V_7_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln122_reg_513, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (icmp_ln122_reg_513 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xi1_s_M_elems_V_7_write <= ap_const_logic_1;
        else 
            xi1_s_M_elems_V_7_write <= ap_const_logic_0;
        end if; 
    end process;


    xi2_s_M_elems_V_0_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xi2_s_M_elems_V_0_full_n, trunc_ln121_reg_509, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_0))) then 
            xi2_s_M_elems_V_0_blk_n <= xi2_s_M_elems_V_0_full_n;
        else 
            xi2_s_M_elems_V_0_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xi2_s_M_elems_V_0_din <= bitcast_ln118_reg_458;

    xi2_s_M_elems_V_0_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln121_reg_509, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_0))) then 
            xi2_s_M_elems_V_0_write <= ap_const_logic_1;
        else 
            xi2_s_M_elems_V_0_write <= ap_const_logic_0;
        end if; 
    end process;


    xi2_s_M_elems_V_1_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xi2_s_M_elems_V_1_full_n, trunc_ln121_reg_509, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_0))) then 
            xi2_s_M_elems_V_1_blk_n <= xi2_s_M_elems_V_1_full_n;
        else 
            xi2_s_M_elems_V_1_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xi2_s_M_elems_V_1_din <= bitcast_ln118_1_reg_470;

    xi2_s_M_elems_V_1_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln121_reg_509, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_0))) then 
            xi2_s_M_elems_V_1_write <= ap_const_logic_1;
        else 
            xi2_s_M_elems_V_1_write <= ap_const_logic_0;
        end if; 
    end process;


    xi2_s_M_elems_V_2_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xi2_s_M_elems_V_2_full_n, trunc_ln121_reg_509, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_0))) then 
            xi2_s_M_elems_V_2_blk_n <= xi2_s_M_elems_V_2_full_n;
        else 
            xi2_s_M_elems_V_2_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xi2_s_M_elems_V_2_din <= bitcast_ln118_2_reg_482;

    xi2_s_M_elems_V_2_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln121_reg_509, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_0))) then 
            xi2_s_M_elems_V_2_write <= ap_const_logic_1;
        else 
            xi2_s_M_elems_V_2_write <= ap_const_logic_0;
        end if; 
    end process;


    xi2_s_M_elems_V_3_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xi2_s_M_elems_V_3_full_n, icmp_ln122_reg_513, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (icmp_ln122_reg_513 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xi2_s_M_elems_V_3_blk_n <= xi2_s_M_elems_V_3_full_n;
        else 
            xi2_s_M_elems_V_3_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xi2_s_M_elems_V_3_din <= bitcast_ln118_3_reg_494;

    xi2_s_M_elems_V_3_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln122_reg_513, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (icmp_ln122_reg_513 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xi2_s_M_elems_V_3_write <= ap_const_logic_1;
        else 
            xi2_s_M_elems_V_3_write <= ap_const_logic_0;
        end if; 
    end process;


    xi2_s_M_elems_V_4_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xi2_s_M_elems_V_4_full_n, trunc_ln121_reg_509, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_1))) then 
            xi2_s_M_elems_V_4_blk_n <= xi2_s_M_elems_V_4_full_n;
        else 
            xi2_s_M_elems_V_4_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xi2_s_M_elems_V_4_din <= bitcast_ln118_reg_458;

    xi2_s_M_elems_V_4_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln121_reg_509, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_1))) then 
            xi2_s_M_elems_V_4_write <= ap_const_logic_1;
        else 
            xi2_s_M_elems_V_4_write <= ap_const_logic_0;
        end if; 
    end process;


    xi2_s_M_elems_V_5_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xi2_s_M_elems_V_5_full_n, trunc_ln121_reg_509, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_1))) then 
            xi2_s_M_elems_V_5_blk_n <= xi2_s_M_elems_V_5_full_n;
        else 
            xi2_s_M_elems_V_5_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xi2_s_M_elems_V_5_din <= bitcast_ln118_1_reg_470;

    xi2_s_M_elems_V_5_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln121_reg_509, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_1))) then 
            xi2_s_M_elems_V_5_write <= ap_const_logic_1;
        else 
            xi2_s_M_elems_V_5_write <= ap_const_logic_0;
        end if; 
    end process;


    xi2_s_M_elems_V_6_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xi2_s_M_elems_V_6_full_n, trunc_ln121_reg_509, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_1))) then 
            xi2_s_M_elems_V_6_blk_n <= xi2_s_M_elems_V_6_full_n;
        else 
            xi2_s_M_elems_V_6_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xi2_s_M_elems_V_6_din <= bitcast_ln118_2_reg_482;

    xi2_s_M_elems_V_6_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln121_reg_509, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_1))) then 
            xi2_s_M_elems_V_6_write <= ap_const_logic_1;
        else 
            xi2_s_M_elems_V_6_write <= ap_const_logic_0;
        end if; 
    end process;


    xi2_s_M_elems_V_7_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xi2_s_M_elems_V_7_full_n, icmp_ln122_reg_513, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (icmp_ln122_reg_513 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xi2_s_M_elems_V_7_blk_n <= xi2_s_M_elems_V_7_full_n;
        else 
            xi2_s_M_elems_V_7_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xi2_s_M_elems_V_7_din <= bitcast_ln118_3_reg_494;

    xi2_s_M_elems_V_7_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln122_reg_513, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (icmp_ln122_reg_513 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xi2_s_M_elems_V_7_write <= ap_const_logic_1;
        else 
            xi2_s_M_elems_V_7_write <= ap_const_logic_0;
        end if; 
    end process;


    xi3_s_M_elems_V_0_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xi3_s_M_elems_V_0_full_n, trunc_ln121_reg_509, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_0))) then 
            xi3_s_M_elems_V_0_blk_n <= xi3_s_M_elems_V_0_full_n;
        else 
            xi3_s_M_elems_V_0_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xi3_s_M_elems_V_0_din <= bitcast_ln118_reg_458;

    xi3_s_M_elems_V_0_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln121_reg_509, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_0))) then 
            xi3_s_M_elems_V_0_write <= ap_const_logic_1;
        else 
            xi3_s_M_elems_V_0_write <= ap_const_logic_0;
        end if; 
    end process;


    xi3_s_M_elems_V_1_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xi3_s_M_elems_V_1_full_n, trunc_ln121_reg_509, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_0))) then 
            xi3_s_M_elems_V_1_blk_n <= xi3_s_M_elems_V_1_full_n;
        else 
            xi3_s_M_elems_V_1_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xi3_s_M_elems_V_1_din <= bitcast_ln118_1_reg_470;

    xi3_s_M_elems_V_1_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln121_reg_509, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_0))) then 
            xi3_s_M_elems_V_1_write <= ap_const_logic_1;
        else 
            xi3_s_M_elems_V_1_write <= ap_const_logic_0;
        end if; 
    end process;


    xi3_s_M_elems_V_2_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xi3_s_M_elems_V_2_full_n, trunc_ln121_reg_509, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_0))) then 
            xi3_s_M_elems_V_2_blk_n <= xi3_s_M_elems_V_2_full_n;
        else 
            xi3_s_M_elems_V_2_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xi3_s_M_elems_V_2_din <= bitcast_ln118_2_reg_482;

    xi3_s_M_elems_V_2_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln121_reg_509, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_0))) then 
            xi3_s_M_elems_V_2_write <= ap_const_logic_1;
        else 
            xi3_s_M_elems_V_2_write <= ap_const_logic_0;
        end if; 
    end process;


    xi3_s_M_elems_V_3_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xi3_s_M_elems_V_3_full_n, icmp_ln122_reg_513, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (icmp_ln122_reg_513 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xi3_s_M_elems_V_3_blk_n <= xi3_s_M_elems_V_3_full_n;
        else 
            xi3_s_M_elems_V_3_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xi3_s_M_elems_V_3_din <= bitcast_ln118_3_reg_494;

    xi3_s_M_elems_V_3_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln122_reg_513, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (icmp_ln122_reg_513 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xi3_s_M_elems_V_3_write <= ap_const_logic_1;
        else 
            xi3_s_M_elems_V_3_write <= ap_const_logic_0;
        end if; 
    end process;


    xi3_s_M_elems_V_4_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xi3_s_M_elems_V_4_full_n, trunc_ln121_reg_509, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_1))) then 
            xi3_s_M_elems_V_4_blk_n <= xi3_s_M_elems_V_4_full_n;
        else 
            xi3_s_M_elems_V_4_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xi3_s_M_elems_V_4_din <= bitcast_ln118_reg_458;

    xi3_s_M_elems_V_4_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln121_reg_509, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_1))) then 
            xi3_s_M_elems_V_4_write <= ap_const_logic_1;
        else 
            xi3_s_M_elems_V_4_write <= ap_const_logic_0;
        end if; 
    end process;


    xi3_s_M_elems_V_5_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xi3_s_M_elems_V_5_full_n, trunc_ln121_reg_509, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_1))) then 
            xi3_s_M_elems_V_5_blk_n <= xi3_s_M_elems_V_5_full_n;
        else 
            xi3_s_M_elems_V_5_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xi3_s_M_elems_V_5_din <= bitcast_ln118_1_reg_470;

    xi3_s_M_elems_V_5_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln121_reg_509, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_1))) then 
            xi3_s_M_elems_V_5_write <= ap_const_logic_1;
        else 
            xi3_s_M_elems_V_5_write <= ap_const_logic_0;
        end if; 
    end process;


    xi3_s_M_elems_V_6_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xi3_s_M_elems_V_6_full_n, trunc_ln121_reg_509, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_1))) then 
            xi3_s_M_elems_V_6_blk_n <= xi3_s_M_elems_V_6_full_n;
        else 
            xi3_s_M_elems_V_6_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xi3_s_M_elems_V_6_din <= bitcast_ln118_2_reg_482;

    xi3_s_M_elems_V_6_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln121_reg_509, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln121_reg_509 = ap_const_lv1_1))) then 
            xi3_s_M_elems_V_6_write <= ap_const_logic_1;
        else 
            xi3_s_M_elems_V_6_write <= ap_const_logic_0;
        end if; 
    end process;


    xi3_s_M_elems_V_7_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xi3_s_M_elems_V_7_full_n, icmp_ln122_reg_513, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (icmp_ln122_reg_513 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xi3_s_M_elems_V_7_blk_n <= xi3_s_M_elems_V_7_full_n;
        else 
            xi3_s_M_elems_V_7_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xi3_s_M_elems_V_7_din <= bitcast_ln118_3_reg_494;

    xi3_s_M_elems_V_7_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln122_reg_513, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (icmp_ln122_reg_513 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xi3_s_M_elems_V_7_write <= ap_const_logic_1;
        else 
            xi3_s_M_elems_V_7_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
