-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Macro_MAC_Acc4_top is
port (
    out_r : OUT STD_LOGIC_VECTOR (127 downto 0);
    xi : IN STD_LOGIC_VECTOR (127 downto 0);
    mro0 : IN STD_LOGIC_VECTOR (127 downto 0);
    mro1 : IN STD_LOGIC_VECTOR (127 downto 0);
    mro2 : IN STD_LOGIC_VECTOR (127 downto 0);
    mro3 : IN STD_LOGIC_VECTOR (127 downto 0);
    row : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    out_r_ap_vld : OUT STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC );
end;


architecture behav of Macro_MAC_Acc4_top is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "Macro_MAC_Acc4_top_Macro_MAC_Acc4_top,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=3.520400,HLS_SYN_LAT=2742,HLS_SYN_TPT=2732,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=110405,HLS_SYN_LUT=96553,HLS_VERSION=2024_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal entry_proc_U0_ap_start : STD_LOGIC;
    signal entry_proc_U0_ap_done : STD_LOGIC;
    signal entry_proc_U0_ap_continue : STD_LOGIC;
    signal entry_proc_U0_ap_idle : STD_LOGIC;
    signal entry_proc_U0_ap_ready : STD_LOGIC;
    signal entry_proc_U0_start_out : STD_LOGIC;
    signal entry_proc_U0_start_write : STD_LOGIC;
    signal entry_proc_U0_xi_c_din : STD_LOGIC_VECTOR (127 downto 0);
    signal entry_proc_U0_xi_c_write : STD_LOGIC;
    signal entry_proc_U0_mro0_c_din : STD_LOGIC_VECTOR (127 downto 0);
    signal entry_proc_U0_mro0_c_write : STD_LOGIC;
    signal entry_proc_U0_mro1_c_din : STD_LOGIC_VECTOR (127 downto 0);
    signal entry_proc_U0_mro1_c_write : STD_LOGIC;
    signal entry_proc_U0_mro2_c_din : STD_LOGIC_VECTOR (127 downto 0);
    signal entry_proc_U0_mro2_c_write : STD_LOGIC;
    signal entry_proc_U0_mro3_c_din : STD_LOGIC_VECTOR (127 downto 0);
    signal entry_proc_U0_mro3_c_write : STD_LOGIC;
    signal entry_proc_U0_row_c_din : STD_LOGIC_VECTOR (15 downto 0);
    signal entry_proc_U0_row_c_write : STD_LOGIC;
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_start : STD_LOGIC;
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_done : STD_LOGIC;
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_continue : STD_LOGIC;
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_idle : STD_LOGIC;
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_ready : STD_LOGIC;
    signal Loop_VITIS_LOOP_324_2_proc_U0_wide_trip_count_read : STD_LOGIC;
    signal Loop_VITIS_LOOP_324_2_proc_U0_xi_read : STD_LOGIC;
    signal Loop_VITIS_LOOP_324_2_proc_U0_mro0_read : STD_LOGIC;
    signal Loop_VITIS_LOOP_324_2_proc_U0_mro1_read : STD_LOGIC;
    signal Loop_VITIS_LOOP_324_2_proc_U0_mro2_read : STD_LOGIC;
    signal Loop_VITIS_LOOP_324_2_proc_U0_mro3_read : STD_LOGIC;
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_return_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_return_2 : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_return_3 : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_return_4 : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_return_5 : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_return_6 : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_return_7 : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_return_8 : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_return_9 : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_return_10 : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_return_11 : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_return_12 : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_return_13 : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_return_14 : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_return_15 : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_return_16 : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_return_17 : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_return_18 : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_return_19 : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_return_20 : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_return_21 : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_return_22 : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_return_23 : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_return_24 : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_return_25 : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_return_26 : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_return_27 : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_return_28 : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_return_29 : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_return_30 : STD_LOGIC_VECTOR (31 downto 0);
    signal Loop_VITIS_LOOP_324_2_proc_U0_ap_return_31 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_channel_done_pout_local3_7 : STD_LOGIC;
    signal pout_local3_7_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_pout_local3_7 : STD_LOGIC := '0';
    signal ap_sync_channel_write_pout_local3_7 : STD_LOGIC;
    signal Loop_VITIS_LOOP_337_3_proc_U0_ap_start : STD_LOGIC;
    signal Loop_VITIS_LOOP_337_3_proc_U0_ap_done : STD_LOGIC;
    signal Loop_VITIS_LOOP_337_3_proc_U0_ap_continue : STD_LOGIC;
    signal Loop_VITIS_LOOP_337_3_proc_U0_ap_idle : STD_LOGIC;
    signal Loop_VITIS_LOOP_337_3_proc_U0_ap_ready : STD_LOGIC;
    signal Loop_VITIS_LOOP_337_3_proc_U0_out_r : STD_LOGIC_VECTOR (127 downto 0);
    signal Loop_VITIS_LOOP_337_3_proc_U0_out_r_ap_vld : STD_LOGIC;
    signal xi_c_full_n : STD_LOGIC;
    signal xi_c_dout : STD_LOGIC_VECTOR (127 downto 0);
    signal xi_c_empty_n : STD_LOGIC;
    signal xi_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal xi_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal mro0_c_full_n : STD_LOGIC;
    signal mro0_c_dout : STD_LOGIC_VECTOR (127 downto 0);
    signal mro0_c_empty_n : STD_LOGIC;
    signal mro0_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal mro0_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal mro1_c_full_n : STD_LOGIC;
    signal mro1_c_dout : STD_LOGIC_VECTOR (127 downto 0);
    signal mro1_c_empty_n : STD_LOGIC;
    signal mro1_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal mro1_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal mro2_c_full_n : STD_LOGIC;
    signal mro2_c_dout : STD_LOGIC_VECTOR (127 downto 0);
    signal mro2_c_empty_n : STD_LOGIC;
    signal mro2_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal mro2_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal mro3_c_full_n : STD_LOGIC;
    signal mro3_c_dout : STD_LOGIC_VECTOR (127 downto 0);
    signal mro3_c_empty_n : STD_LOGIC;
    signal mro3_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal mro3_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal row_c_full_n : STD_LOGIC;
    signal row_c_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal row_c_empty_n : STD_LOGIC;
    signal row_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal row_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local0_full_n : STD_LOGIC;
    signal pout_local0_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal pout_local0_empty_n : STD_LOGIC;
    signal pout_local0_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local0_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local0_1_full_n : STD_LOGIC;
    signal pout_local0_1_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal pout_local0_1_empty_n : STD_LOGIC;
    signal pout_local0_1_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local0_1_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local0_2_full_n : STD_LOGIC;
    signal pout_local0_2_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal pout_local0_2_empty_n : STD_LOGIC;
    signal pout_local0_2_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local0_2_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local0_3_full_n : STD_LOGIC;
    signal pout_local0_3_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal pout_local0_3_empty_n : STD_LOGIC;
    signal pout_local0_3_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local0_3_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local0_4_full_n : STD_LOGIC;
    signal pout_local0_4_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal pout_local0_4_empty_n : STD_LOGIC;
    signal pout_local0_4_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local0_4_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local0_5_full_n : STD_LOGIC;
    signal pout_local0_5_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal pout_local0_5_empty_n : STD_LOGIC;
    signal pout_local0_5_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local0_5_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local0_6_full_n : STD_LOGIC;
    signal pout_local0_6_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal pout_local0_6_empty_n : STD_LOGIC;
    signal pout_local0_6_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local0_6_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local0_7_full_n : STD_LOGIC;
    signal pout_local0_7_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal pout_local0_7_empty_n : STD_LOGIC;
    signal pout_local0_7_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local0_7_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local1_full_n : STD_LOGIC;
    signal pout_local1_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal pout_local1_empty_n : STD_LOGIC;
    signal pout_local1_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local1_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local1_1_full_n : STD_LOGIC;
    signal pout_local1_1_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal pout_local1_1_empty_n : STD_LOGIC;
    signal pout_local1_1_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local1_1_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local1_2_full_n : STD_LOGIC;
    signal pout_local1_2_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal pout_local1_2_empty_n : STD_LOGIC;
    signal pout_local1_2_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local1_2_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local1_3_full_n : STD_LOGIC;
    signal pout_local1_3_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal pout_local1_3_empty_n : STD_LOGIC;
    signal pout_local1_3_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local1_3_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local1_4_full_n : STD_LOGIC;
    signal pout_local1_4_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal pout_local1_4_empty_n : STD_LOGIC;
    signal pout_local1_4_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local1_4_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local1_5_full_n : STD_LOGIC;
    signal pout_local1_5_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal pout_local1_5_empty_n : STD_LOGIC;
    signal pout_local1_5_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local1_5_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local1_6_full_n : STD_LOGIC;
    signal pout_local1_6_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal pout_local1_6_empty_n : STD_LOGIC;
    signal pout_local1_6_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local1_6_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local1_7_full_n : STD_LOGIC;
    signal pout_local1_7_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal pout_local1_7_empty_n : STD_LOGIC;
    signal pout_local1_7_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local1_7_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local2_full_n : STD_LOGIC;
    signal pout_local2_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal pout_local2_empty_n : STD_LOGIC;
    signal pout_local2_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local2_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local2_1_full_n : STD_LOGIC;
    signal pout_local2_1_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal pout_local2_1_empty_n : STD_LOGIC;
    signal pout_local2_1_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local2_1_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local2_2_full_n : STD_LOGIC;
    signal pout_local2_2_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal pout_local2_2_empty_n : STD_LOGIC;
    signal pout_local2_2_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local2_2_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local2_3_full_n : STD_LOGIC;
    signal pout_local2_3_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal pout_local2_3_empty_n : STD_LOGIC;
    signal pout_local2_3_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local2_3_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local2_4_full_n : STD_LOGIC;
    signal pout_local2_4_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal pout_local2_4_empty_n : STD_LOGIC;
    signal pout_local2_4_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local2_4_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local2_5_full_n : STD_LOGIC;
    signal pout_local2_5_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal pout_local2_5_empty_n : STD_LOGIC;
    signal pout_local2_5_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local2_5_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local2_6_full_n : STD_LOGIC;
    signal pout_local2_6_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal pout_local2_6_empty_n : STD_LOGIC;
    signal pout_local2_6_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local2_6_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local2_7_full_n : STD_LOGIC;
    signal pout_local2_7_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal pout_local2_7_empty_n : STD_LOGIC;
    signal pout_local2_7_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local2_7_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local3_full_n : STD_LOGIC;
    signal pout_local3_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal pout_local3_empty_n : STD_LOGIC;
    signal pout_local3_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local3_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local3_1_full_n : STD_LOGIC;
    signal pout_local3_1_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal pout_local3_1_empty_n : STD_LOGIC;
    signal pout_local3_1_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local3_1_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local3_2_full_n : STD_LOGIC;
    signal pout_local3_2_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal pout_local3_2_empty_n : STD_LOGIC;
    signal pout_local3_2_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local3_2_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local3_3_full_n : STD_LOGIC;
    signal pout_local3_3_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal pout_local3_3_empty_n : STD_LOGIC;
    signal pout_local3_3_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local3_3_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local3_4_full_n : STD_LOGIC;
    signal pout_local3_4_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal pout_local3_4_empty_n : STD_LOGIC;
    signal pout_local3_4_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local3_4_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local3_5_full_n : STD_LOGIC;
    signal pout_local3_5_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal pout_local3_5_empty_n : STD_LOGIC;
    signal pout_local3_5_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local3_5_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local3_6_full_n : STD_LOGIC;
    signal pout_local3_6_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal pout_local3_6_empty_n : STD_LOGIC;
    signal pout_local3_6_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local3_6_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local3_7_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal pout_local3_7_empty_n : STD_LOGIC;
    signal pout_local3_7_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal pout_local3_7_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal start_for_Loop_VITIS_LOOP_324_2_proc_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Loop_VITIS_LOOP_324_2_proc_U0_full_n : STD_LOGIC;
    signal start_for_Loop_VITIS_LOOP_324_2_proc_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Loop_VITIS_LOOP_324_2_proc_U0_empty_n : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component Macro_MAC_Acc4_top_entry_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        xi : IN STD_LOGIC_VECTOR (127 downto 0);
        xi_c_din : OUT STD_LOGIC_VECTOR (127 downto 0);
        xi_c_full_n : IN STD_LOGIC;
        xi_c_write : OUT STD_LOGIC;
        xi_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        xi_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        mro0 : IN STD_LOGIC_VECTOR (127 downto 0);
        mro0_c_din : OUT STD_LOGIC_VECTOR (127 downto 0);
        mro0_c_full_n : IN STD_LOGIC;
        mro0_c_write : OUT STD_LOGIC;
        mro0_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        mro0_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        mro1 : IN STD_LOGIC_VECTOR (127 downto 0);
        mro1_c_din : OUT STD_LOGIC_VECTOR (127 downto 0);
        mro1_c_full_n : IN STD_LOGIC;
        mro1_c_write : OUT STD_LOGIC;
        mro1_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        mro1_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        mro2 : IN STD_LOGIC_VECTOR (127 downto 0);
        mro2_c_din : OUT STD_LOGIC_VECTOR (127 downto 0);
        mro2_c_full_n : IN STD_LOGIC;
        mro2_c_write : OUT STD_LOGIC;
        mro2_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        mro2_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        mro3 : IN STD_LOGIC_VECTOR (127 downto 0);
        mro3_c_din : OUT STD_LOGIC_VECTOR (127 downto 0);
        mro3_c_full_n : IN STD_LOGIC;
        mro3_c_write : OUT STD_LOGIC;
        mro3_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        mro3_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        row : IN STD_LOGIC_VECTOR (15 downto 0);
        row_c_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        row_c_full_n : IN STD_LOGIC;
        row_c_write : OUT STD_LOGIC;
        row_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        row_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component Macro_MAC_Acc4_top_Loop_VITIS_LOOP_324_2_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        wide_trip_count_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        wide_trip_count_empty_n : IN STD_LOGIC;
        wide_trip_count_read : OUT STD_LOGIC;
        wide_trip_count_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        wide_trip_count_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        xi_dout : IN STD_LOGIC_VECTOR (127 downto 0);
        xi_empty_n : IN STD_LOGIC;
        xi_read : OUT STD_LOGIC;
        xi_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        xi_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        mro0_dout : IN STD_LOGIC_VECTOR (127 downto 0);
        mro0_empty_n : IN STD_LOGIC;
        mro0_read : OUT STD_LOGIC;
        mro0_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        mro0_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        mro1_dout : IN STD_LOGIC_VECTOR (127 downto 0);
        mro1_empty_n : IN STD_LOGIC;
        mro1_read : OUT STD_LOGIC;
        mro1_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        mro1_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        mro2_dout : IN STD_LOGIC_VECTOR (127 downto 0);
        mro2_empty_n : IN STD_LOGIC;
        mro2_read : OUT STD_LOGIC;
        mro2_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        mro2_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        mro3_dout : IN STD_LOGIC_VECTOR (127 downto 0);
        mro3_empty_n : IN STD_LOGIC;
        mro3_read : OUT STD_LOGIC;
        mro3_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        mro3_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        p_read : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read2 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read6 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read10 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read14 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read18 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read22 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read26 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read30 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read34 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read38 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read42 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read46 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read50 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read54 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read58 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read62 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read66 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read70 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read74 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read78 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read82 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read86 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read90 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read94 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read98 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read102 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read106 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read110 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read114 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read118 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read122 : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_8 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_9 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_10 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_11 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_12 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_13 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_14 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_15 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_16 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_17 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_18 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_19 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_20 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_21 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_22 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_23 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_24 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_25 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_26 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_27 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_28 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_29 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_30 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_31 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component Macro_MAC_Acc4_top_Loop_VITIS_LOOP_337_3_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read2 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read3 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read4 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read5 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read6 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read7 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read8 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read9 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read10 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read11 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read12 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read13 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read14 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read15 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read16 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read17 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read18 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read19 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read20 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read21 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read22 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read23 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read24 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read25 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read26 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read27 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read28 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read29 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read30 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read31 : IN STD_LOGIC_VECTOR (31 downto 0);
        out_r : OUT STD_LOGIC_VECTOR (127 downto 0);
        out_r_ap_vld : OUT STD_LOGIC );
    end component;


    component Macro_MAC_Acc4_top_fifo_w128_d3_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (127 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (127 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component Macro_MAC_Acc4_top_fifo_w16_d3_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (15 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (15 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component Macro_MAC_Acc4_top_fifo_w32_d2_S_x IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component Macro_MAC_Acc4_top_start_for_Loop_VITIS_LOOP_324_2_proc_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    entry_proc_U0 : component Macro_MAC_Acc4_top_entry_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => entry_proc_U0_ap_start,
        start_full_n => start_for_Loop_VITIS_LOOP_324_2_proc_U0_full_n,
        ap_done => entry_proc_U0_ap_done,
        ap_continue => entry_proc_U0_ap_continue,
        ap_idle => entry_proc_U0_ap_idle,
        ap_ready => entry_proc_U0_ap_ready,
        start_out => entry_proc_U0_start_out,
        start_write => entry_proc_U0_start_write,
        xi => xi,
        xi_c_din => entry_proc_U0_xi_c_din,
        xi_c_full_n => xi_c_full_n,
        xi_c_write => entry_proc_U0_xi_c_write,
        xi_c_num_data_valid => xi_c_num_data_valid,
        xi_c_fifo_cap => xi_c_fifo_cap,
        mro0 => mro0,
        mro0_c_din => entry_proc_U0_mro0_c_din,
        mro0_c_full_n => mro0_c_full_n,
        mro0_c_write => entry_proc_U0_mro0_c_write,
        mro0_c_num_data_valid => mro0_c_num_data_valid,
        mro0_c_fifo_cap => mro0_c_fifo_cap,
        mro1 => mro1,
        mro1_c_din => entry_proc_U0_mro1_c_din,
        mro1_c_full_n => mro1_c_full_n,
        mro1_c_write => entry_proc_U0_mro1_c_write,
        mro1_c_num_data_valid => mro1_c_num_data_valid,
        mro1_c_fifo_cap => mro1_c_fifo_cap,
        mro2 => mro2,
        mro2_c_din => entry_proc_U0_mro2_c_din,
        mro2_c_full_n => mro2_c_full_n,
        mro2_c_write => entry_proc_U0_mro2_c_write,
        mro2_c_num_data_valid => mro2_c_num_data_valid,
        mro2_c_fifo_cap => mro2_c_fifo_cap,
        mro3 => mro3,
        mro3_c_din => entry_proc_U0_mro3_c_din,
        mro3_c_full_n => mro3_c_full_n,
        mro3_c_write => entry_proc_U0_mro3_c_write,
        mro3_c_num_data_valid => mro3_c_num_data_valid,
        mro3_c_fifo_cap => mro3_c_fifo_cap,
        row => row,
        row_c_din => entry_proc_U0_row_c_din,
        row_c_full_n => row_c_full_n,
        row_c_write => entry_proc_U0_row_c_write,
        row_c_num_data_valid => row_c_num_data_valid,
        row_c_fifo_cap => row_c_fifo_cap);

    Loop_VITIS_LOOP_324_2_proc_U0 : component Macro_MAC_Acc4_top_Loop_VITIS_LOOP_324_2_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => Loop_VITIS_LOOP_324_2_proc_U0_ap_start,
        ap_done => Loop_VITIS_LOOP_324_2_proc_U0_ap_done,
        ap_continue => Loop_VITIS_LOOP_324_2_proc_U0_ap_continue,
        ap_idle => Loop_VITIS_LOOP_324_2_proc_U0_ap_idle,
        ap_ready => Loop_VITIS_LOOP_324_2_proc_U0_ap_ready,
        wide_trip_count_dout => row_c_dout,
        wide_trip_count_empty_n => row_c_empty_n,
        wide_trip_count_read => Loop_VITIS_LOOP_324_2_proc_U0_wide_trip_count_read,
        wide_trip_count_num_data_valid => row_c_num_data_valid,
        wide_trip_count_fifo_cap => row_c_fifo_cap,
        xi_dout => xi_c_dout,
        xi_empty_n => xi_c_empty_n,
        xi_read => Loop_VITIS_LOOP_324_2_proc_U0_xi_read,
        xi_num_data_valid => xi_c_num_data_valid,
        xi_fifo_cap => xi_c_fifo_cap,
        mro0_dout => mro0_c_dout,
        mro0_empty_n => mro0_c_empty_n,
        mro0_read => Loop_VITIS_LOOP_324_2_proc_U0_mro0_read,
        mro0_num_data_valid => mro0_c_num_data_valid,
        mro0_fifo_cap => mro0_c_fifo_cap,
        mro1_dout => mro1_c_dout,
        mro1_empty_n => mro1_c_empty_n,
        mro1_read => Loop_VITIS_LOOP_324_2_proc_U0_mro1_read,
        mro1_num_data_valid => mro1_c_num_data_valid,
        mro1_fifo_cap => mro1_c_fifo_cap,
        mro2_dout => mro2_c_dout,
        mro2_empty_n => mro2_c_empty_n,
        mro2_read => Loop_VITIS_LOOP_324_2_proc_U0_mro2_read,
        mro2_num_data_valid => mro2_c_num_data_valid,
        mro2_fifo_cap => mro2_c_fifo_cap,
        mro3_dout => mro3_c_dout,
        mro3_empty_n => mro3_c_empty_n,
        mro3_read => Loop_VITIS_LOOP_324_2_proc_U0_mro3_read,
        mro3_num_data_valid => mro3_c_num_data_valid,
        mro3_fifo_cap => mro3_c_fifo_cap,
        p_read => ap_const_lv32_0,
        p_read2 => ap_const_lv32_0,
        p_read6 => ap_const_lv32_0,
        p_read10 => ap_const_lv32_0,
        p_read14 => ap_const_lv32_0,
        p_read18 => ap_const_lv32_0,
        p_read22 => ap_const_lv32_0,
        p_read26 => ap_const_lv32_0,
        p_read30 => ap_const_lv32_0,
        p_read34 => ap_const_lv32_0,
        p_read38 => ap_const_lv32_0,
        p_read42 => ap_const_lv32_0,
        p_read46 => ap_const_lv32_0,
        p_read50 => ap_const_lv32_0,
        p_read54 => ap_const_lv32_0,
        p_read58 => ap_const_lv32_0,
        p_read62 => ap_const_lv32_0,
        p_read66 => ap_const_lv32_0,
        p_read70 => ap_const_lv32_0,
        p_read74 => ap_const_lv32_0,
        p_read78 => ap_const_lv32_0,
        p_read82 => ap_const_lv32_0,
        p_read86 => ap_const_lv32_0,
        p_read90 => ap_const_lv32_0,
        p_read94 => ap_const_lv32_0,
        p_read98 => ap_const_lv32_0,
        p_read102 => ap_const_lv32_0,
        p_read106 => ap_const_lv32_0,
        p_read110 => ap_const_lv32_0,
        p_read114 => ap_const_lv32_0,
        p_read118 => ap_const_lv32_0,
        p_read122 => ap_const_lv32_0,
        ap_return_0 => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_0,
        ap_return_1 => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_1,
        ap_return_2 => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_2,
        ap_return_3 => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_3,
        ap_return_4 => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_4,
        ap_return_5 => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_5,
        ap_return_6 => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_6,
        ap_return_7 => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_7,
        ap_return_8 => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_8,
        ap_return_9 => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_9,
        ap_return_10 => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_10,
        ap_return_11 => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_11,
        ap_return_12 => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_12,
        ap_return_13 => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_13,
        ap_return_14 => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_14,
        ap_return_15 => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_15,
        ap_return_16 => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_16,
        ap_return_17 => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_17,
        ap_return_18 => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_18,
        ap_return_19 => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_19,
        ap_return_20 => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_20,
        ap_return_21 => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_21,
        ap_return_22 => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_22,
        ap_return_23 => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_23,
        ap_return_24 => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_24,
        ap_return_25 => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_25,
        ap_return_26 => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_26,
        ap_return_27 => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_27,
        ap_return_28 => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_28,
        ap_return_29 => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_29,
        ap_return_30 => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_30,
        ap_return_31 => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_31);

    Loop_VITIS_LOOP_337_3_proc_U0 : component Macro_MAC_Acc4_top_Loop_VITIS_LOOP_337_3_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => Loop_VITIS_LOOP_337_3_proc_U0_ap_start,
        ap_done => Loop_VITIS_LOOP_337_3_proc_U0_ap_done,
        ap_continue => Loop_VITIS_LOOP_337_3_proc_U0_ap_continue,
        ap_idle => Loop_VITIS_LOOP_337_3_proc_U0_ap_idle,
        ap_ready => Loop_VITIS_LOOP_337_3_proc_U0_ap_ready,
        p_read => pout_local3_dout,
        p_read1 => pout_local3_4_dout,
        p_read2 => pout_local3_1_dout,
        p_read3 => pout_local3_5_dout,
        p_read4 => pout_local3_2_dout,
        p_read5 => pout_local3_6_dout,
        p_read6 => pout_local3_3_dout,
        p_read7 => pout_local3_7_dout,
        p_read8 => pout_local2_dout,
        p_read9 => pout_local2_4_dout,
        p_read10 => pout_local2_1_dout,
        p_read11 => pout_local2_5_dout,
        p_read12 => pout_local2_2_dout,
        p_read13 => pout_local2_6_dout,
        p_read14 => pout_local2_3_dout,
        p_read15 => pout_local2_7_dout,
        p_read16 => pout_local1_dout,
        p_read17 => pout_local1_4_dout,
        p_read18 => pout_local1_1_dout,
        p_read19 => pout_local1_5_dout,
        p_read20 => pout_local1_2_dout,
        p_read21 => pout_local1_6_dout,
        p_read22 => pout_local1_3_dout,
        p_read23 => pout_local1_7_dout,
        p_read24 => pout_local0_dout,
        p_read25 => pout_local0_4_dout,
        p_read26 => pout_local0_1_dout,
        p_read27 => pout_local0_5_dout,
        p_read28 => pout_local0_2_dout,
        p_read29 => pout_local0_6_dout,
        p_read30 => pout_local0_3_dout,
        p_read31 => pout_local0_7_dout,
        out_r => Loop_VITIS_LOOP_337_3_proc_U0_out_r,
        out_r_ap_vld => Loop_VITIS_LOOP_337_3_proc_U0_out_r_ap_vld);

    xi_c_U : component Macro_MAC_Acc4_top_fifo_w128_d3_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_xi_c_din,
        if_full_n => xi_c_full_n,
        if_write => entry_proc_U0_xi_c_write,
        if_dout => xi_c_dout,
        if_empty_n => xi_c_empty_n,
        if_read => Loop_VITIS_LOOP_324_2_proc_U0_xi_read,
        if_num_data_valid => xi_c_num_data_valid,
        if_fifo_cap => xi_c_fifo_cap);

    mro0_c_U : component Macro_MAC_Acc4_top_fifo_w128_d3_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_mro0_c_din,
        if_full_n => mro0_c_full_n,
        if_write => entry_proc_U0_mro0_c_write,
        if_dout => mro0_c_dout,
        if_empty_n => mro0_c_empty_n,
        if_read => Loop_VITIS_LOOP_324_2_proc_U0_mro0_read,
        if_num_data_valid => mro0_c_num_data_valid,
        if_fifo_cap => mro0_c_fifo_cap);

    mro1_c_U : component Macro_MAC_Acc4_top_fifo_w128_d3_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_mro1_c_din,
        if_full_n => mro1_c_full_n,
        if_write => entry_proc_U0_mro1_c_write,
        if_dout => mro1_c_dout,
        if_empty_n => mro1_c_empty_n,
        if_read => Loop_VITIS_LOOP_324_2_proc_U0_mro1_read,
        if_num_data_valid => mro1_c_num_data_valid,
        if_fifo_cap => mro1_c_fifo_cap);

    mro2_c_U : component Macro_MAC_Acc4_top_fifo_w128_d3_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_mro2_c_din,
        if_full_n => mro2_c_full_n,
        if_write => entry_proc_U0_mro2_c_write,
        if_dout => mro2_c_dout,
        if_empty_n => mro2_c_empty_n,
        if_read => Loop_VITIS_LOOP_324_2_proc_U0_mro2_read,
        if_num_data_valid => mro2_c_num_data_valid,
        if_fifo_cap => mro2_c_fifo_cap);

    mro3_c_U : component Macro_MAC_Acc4_top_fifo_w128_d3_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_mro3_c_din,
        if_full_n => mro3_c_full_n,
        if_write => entry_proc_U0_mro3_c_write,
        if_dout => mro3_c_dout,
        if_empty_n => mro3_c_empty_n,
        if_read => Loop_VITIS_LOOP_324_2_proc_U0_mro3_read,
        if_num_data_valid => mro3_c_num_data_valid,
        if_fifo_cap => mro3_c_fifo_cap);

    row_c_U : component Macro_MAC_Acc4_top_fifo_w16_d3_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_row_c_din,
        if_full_n => row_c_full_n,
        if_write => entry_proc_U0_row_c_write,
        if_dout => row_c_dout,
        if_empty_n => row_c_empty_n,
        if_read => Loop_VITIS_LOOP_324_2_proc_U0_wide_trip_count_read,
        if_num_data_valid => row_c_num_data_valid,
        if_fifo_cap => row_c_fifo_cap);

    pout_local0_U : component Macro_MAC_Acc4_top_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_0,
        if_full_n => pout_local0_full_n,
        if_write => ap_channel_done_pout_local3_7,
        if_dout => pout_local0_dout,
        if_empty_n => pout_local0_empty_n,
        if_read => Loop_VITIS_LOOP_337_3_proc_U0_ap_ready,
        if_num_data_valid => pout_local0_num_data_valid,
        if_fifo_cap => pout_local0_fifo_cap);

    pout_local0_1_U : component Macro_MAC_Acc4_top_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_1,
        if_full_n => pout_local0_1_full_n,
        if_write => ap_channel_done_pout_local3_7,
        if_dout => pout_local0_1_dout,
        if_empty_n => pout_local0_1_empty_n,
        if_read => Loop_VITIS_LOOP_337_3_proc_U0_ap_ready,
        if_num_data_valid => pout_local0_1_num_data_valid,
        if_fifo_cap => pout_local0_1_fifo_cap);

    pout_local0_2_U : component Macro_MAC_Acc4_top_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_2,
        if_full_n => pout_local0_2_full_n,
        if_write => ap_channel_done_pout_local3_7,
        if_dout => pout_local0_2_dout,
        if_empty_n => pout_local0_2_empty_n,
        if_read => Loop_VITIS_LOOP_337_3_proc_U0_ap_ready,
        if_num_data_valid => pout_local0_2_num_data_valid,
        if_fifo_cap => pout_local0_2_fifo_cap);

    pout_local0_3_U : component Macro_MAC_Acc4_top_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_3,
        if_full_n => pout_local0_3_full_n,
        if_write => ap_channel_done_pout_local3_7,
        if_dout => pout_local0_3_dout,
        if_empty_n => pout_local0_3_empty_n,
        if_read => Loop_VITIS_LOOP_337_3_proc_U0_ap_ready,
        if_num_data_valid => pout_local0_3_num_data_valid,
        if_fifo_cap => pout_local0_3_fifo_cap);

    pout_local0_4_U : component Macro_MAC_Acc4_top_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_4,
        if_full_n => pout_local0_4_full_n,
        if_write => ap_channel_done_pout_local3_7,
        if_dout => pout_local0_4_dout,
        if_empty_n => pout_local0_4_empty_n,
        if_read => Loop_VITIS_LOOP_337_3_proc_U0_ap_ready,
        if_num_data_valid => pout_local0_4_num_data_valid,
        if_fifo_cap => pout_local0_4_fifo_cap);

    pout_local0_5_U : component Macro_MAC_Acc4_top_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_5,
        if_full_n => pout_local0_5_full_n,
        if_write => ap_channel_done_pout_local3_7,
        if_dout => pout_local0_5_dout,
        if_empty_n => pout_local0_5_empty_n,
        if_read => Loop_VITIS_LOOP_337_3_proc_U0_ap_ready,
        if_num_data_valid => pout_local0_5_num_data_valid,
        if_fifo_cap => pout_local0_5_fifo_cap);

    pout_local0_6_U : component Macro_MAC_Acc4_top_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_6,
        if_full_n => pout_local0_6_full_n,
        if_write => ap_channel_done_pout_local3_7,
        if_dout => pout_local0_6_dout,
        if_empty_n => pout_local0_6_empty_n,
        if_read => Loop_VITIS_LOOP_337_3_proc_U0_ap_ready,
        if_num_data_valid => pout_local0_6_num_data_valid,
        if_fifo_cap => pout_local0_6_fifo_cap);

    pout_local0_7_U : component Macro_MAC_Acc4_top_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_7,
        if_full_n => pout_local0_7_full_n,
        if_write => ap_channel_done_pout_local3_7,
        if_dout => pout_local0_7_dout,
        if_empty_n => pout_local0_7_empty_n,
        if_read => Loop_VITIS_LOOP_337_3_proc_U0_ap_ready,
        if_num_data_valid => pout_local0_7_num_data_valid,
        if_fifo_cap => pout_local0_7_fifo_cap);

    pout_local1_U : component Macro_MAC_Acc4_top_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_8,
        if_full_n => pout_local1_full_n,
        if_write => ap_channel_done_pout_local3_7,
        if_dout => pout_local1_dout,
        if_empty_n => pout_local1_empty_n,
        if_read => Loop_VITIS_LOOP_337_3_proc_U0_ap_ready,
        if_num_data_valid => pout_local1_num_data_valid,
        if_fifo_cap => pout_local1_fifo_cap);

    pout_local1_1_U : component Macro_MAC_Acc4_top_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_9,
        if_full_n => pout_local1_1_full_n,
        if_write => ap_channel_done_pout_local3_7,
        if_dout => pout_local1_1_dout,
        if_empty_n => pout_local1_1_empty_n,
        if_read => Loop_VITIS_LOOP_337_3_proc_U0_ap_ready,
        if_num_data_valid => pout_local1_1_num_data_valid,
        if_fifo_cap => pout_local1_1_fifo_cap);

    pout_local1_2_U : component Macro_MAC_Acc4_top_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_10,
        if_full_n => pout_local1_2_full_n,
        if_write => ap_channel_done_pout_local3_7,
        if_dout => pout_local1_2_dout,
        if_empty_n => pout_local1_2_empty_n,
        if_read => Loop_VITIS_LOOP_337_3_proc_U0_ap_ready,
        if_num_data_valid => pout_local1_2_num_data_valid,
        if_fifo_cap => pout_local1_2_fifo_cap);

    pout_local1_3_U : component Macro_MAC_Acc4_top_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_11,
        if_full_n => pout_local1_3_full_n,
        if_write => ap_channel_done_pout_local3_7,
        if_dout => pout_local1_3_dout,
        if_empty_n => pout_local1_3_empty_n,
        if_read => Loop_VITIS_LOOP_337_3_proc_U0_ap_ready,
        if_num_data_valid => pout_local1_3_num_data_valid,
        if_fifo_cap => pout_local1_3_fifo_cap);

    pout_local1_4_U : component Macro_MAC_Acc4_top_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_12,
        if_full_n => pout_local1_4_full_n,
        if_write => ap_channel_done_pout_local3_7,
        if_dout => pout_local1_4_dout,
        if_empty_n => pout_local1_4_empty_n,
        if_read => Loop_VITIS_LOOP_337_3_proc_U0_ap_ready,
        if_num_data_valid => pout_local1_4_num_data_valid,
        if_fifo_cap => pout_local1_4_fifo_cap);

    pout_local1_5_U : component Macro_MAC_Acc4_top_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_13,
        if_full_n => pout_local1_5_full_n,
        if_write => ap_channel_done_pout_local3_7,
        if_dout => pout_local1_5_dout,
        if_empty_n => pout_local1_5_empty_n,
        if_read => Loop_VITIS_LOOP_337_3_proc_U0_ap_ready,
        if_num_data_valid => pout_local1_5_num_data_valid,
        if_fifo_cap => pout_local1_5_fifo_cap);

    pout_local1_6_U : component Macro_MAC_Acc4_top_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_14,
        if_full_n => pout_local1_6_full_n,
        if_write => ap_channel_done_pout_local3_7,
        if_dout => pout_local1_6_dout,
        if_empty_n => pout_local1_6_empty_n,
        if_read => Loop_VITIS_LOOP_337_3_proc_U0_ap_ready,
        if_num_data_valid => pout_local1_6_num_data_valid,
        if_fifo_cap => pout_local1_6_fifo_cap);

    pout_local1_7_U : component Macro_MAC_Acc4_top_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_15,
        if_full_n => pout_local1_7_full_n,
        if_write => ap_channel_done_pout_local3_7,
        if_dout => pout_local1_7_dout,
        if_empty_n => pout_local1_7_empty_n,
        if_read => Loop_VITIS_LOOP_337_3_proc_U0_ap_ready,
        if_num_data_valid => pout_local1_7_num_data_valid,
        if_fifo_cap => pout_local1_7_fifo_cap);

    pout_local2_U : component Macro_MAC_Acc4_top_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_16,
        if_full_n => pout_local2_full_n,
        if_write => ap_channel_done_pout_local3_7,
        if_dout => pout_local2_dout,
        if_empty_n => pout_local2_empty_n,
        if_read => Loop_VITIS_LOOP_337_3_proc_U0_ap_ready,
        if_num_data_valid => pout_local2_num_data_valid,
        if_fifo_cap => pout_local2_fifo_cap);

    pout_local2_1_U : component Macro_MAC_Acc4_top_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_17,
        if_full_n => pout_local2_1_full_n,
        if_write => ap_channel_done_pout_local3_7,
        if_dout => pout_local2_1_dout,
        if_empty_n => pout_local2_1_empty_n,
        if_read => Loop_VITIS_LOOP_337_3_proc_U0_ap_ready,
        if_num_data_valid => pout_local2_1_num_data_valid,
        if_fifo_cap => pout_local2_1_fifo_cap);

    pout_local2_2_U : component Macro_MAC_Acc4_top_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_18,
        if_full_n => pout_local2_2_full_n,
        if_write => ap_channel_done_pout_local3_7,
        if_dout => pout_local2_2_dout,
        if_empty_n => pout_local2_2_empty_n,
        if_read => Loop_VITIS_LOOP_337_3_proc_U0_ap_ready,
        if_num_data_valid => pout_local2_2_num_data_valid,
        if_fifo_cap => pout_local2_2_fifo_cap);

    pout_local2_3_U : component Macro_MAC_Acc4_top_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_19,
        if_full_n => pout_local2_3_full_n,
        if_write => ap_channel_done_pout_local3_7,
        if_dout => pout_local2_3_dout,
        if_empty_n => pout_local2_3_empty_n,
        if_read => Loop_VITIS_LOOP_337_3_proc_U0_ap_ready,
        if_num_data_valid => pout_local2_3_num_data_valid,
        if_fifo_cap => pout_local2_3_fifo_cap);

    pout_local2_4_U : component Macro_MAC_Acc4_top_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_20,
        if_full_n => pout_local2_4_full_n,
        if_write => ap_channel_done_pout_local3_7,
        if_dout => pout_local2_4_dout,
        if_empty_n => pout_local2_4_empty_n,
        if_read => Loop_VITIS_LOOP_337_3_proc_U0_ap_ready,
        if_num_data_valid => pout_local2_4_num_data_valid,
        if_fifo_cap => pout_local2_4_fifo_cap);

    pout_local2_5_U : component Macro_MAC_Acc4_top_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_21,
        if_full_n => pout_local2_5_full_n,
        if_write => ap_channel_done_pout_local3_7,
        if_dout => pout_local2_5_dout,
        if_empty_n => pout_local2_5_empty_n,
        if_read => Loop_VITIS_LOOP_337_3_proc_U0_ap_ready,
        if_num_data_valid => pout_local2_5_num_data_valid,
        if_fifo_cap => pout_local2_5_fifo_cap);

    pout_local2_6_U : component Macro_MAC_Acc4_top_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_22,
        if_full_n => pout_local2_6_full_n,
        if_write => ap_channel_done_pout_local3_7,
        if_dout => pout_local2_6_dout,
        if_empty_n => pout_local2_6_empty_n,
        if_read => Loop_VITIS_LOOP_337_3_proc_U0_ap_ready,
        if_num_data_valid => pout_local2_6_num_data_valid,
        if_fifo_cap => pout_local2_6_fifo_cap);

    pout_local2_7_U : component Macro_MAC_Acc4_top_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_23,
        if_full_n => pout_local2_7_full_n,
        if_write => ap_channel_done_pout_local3_7,
        if_dout => pout_local2_7_dout,
        if_empty_n => pout_local2_7_empty_n,
        if_read => Loop_VITIS_LOOP_337_3_proc_U0_ap_ready,
        if_num_data_valid => pout_local2_7_num_data_valid,
        if_fifo_cap => pout_local2_7_fifo_cap);

    pout_local3_U : component Macro_MAC_Acc4_top_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_24,
        if_full_n => pout_local3_full_n,
        if_write => ap_channel_done_pout_local3_7,
        if_dout => pout_local3_dout,
        if_empty_n => pout_local3_empty_n,
        if_read => Loop_VITIS_LOOP_337_3_proc_U0_ap_ready,
        if_num_data_valid => pout_local3_num_data_valid,
        if_fifo_cap => pout_local3_fifo_cap);

    pout_local3_1_U : component Macro_MAC_Acc4_top_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_25,
        if_full_n => pout_local3_1_full_n,
        if_write => ap_channel_done_pout_local3_7,
        if_dout => pout_local3_1_dout,
        if_empty_n => pout_local3_1_empty_n,
        if_read => Loop_VITIS_LOOP_337_3_proc_U0_ap_ready,
        if_num_data_valid => pout_local3_1_num_data_valid,
        if_fifo_cap => pout_local3_1_fifo_cap);

    pout_local3_2_U : component Macro_MAC_Acc4_top_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_26,
        if_full_n => pout_local3_2_full_n,
        if_write => ap_channel_done_pout_local3_7,
        if_dout => pout_local3_2_dout,
        if_empty_n => pout_local3_2_empty_n,
        if_read => Loop_VITIS_LOOP_337_3_proc_U0_ap_ready,
        if_num_data_valid => pout_local3_2_num_data_valid,
        if_fifo_cap => pout_local3_2_fifo_cap);

    pout_local3_3_U : component Macro_MAC_Acc4_top_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_27,
        if_full_n => pout_local3_3_full_n,
        if_write => ap_channel_done_pout_local3_7,
        if_dout => pout_local3_3_dout,
        if_empty_n => pout_local3_3_empty_n,
        if_read => Loop_VITIS_LOOP_337_3_proc_U0_ap_ready,
        if_num_data_valid => pout_local3_3_num_data_valid,
        if_fifo_cap => pout_local3_3_fifo_cap);

    pout_local3_4_U : component Macro_MAC_Acc4_top_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_28,
        if_full_n => pout_local3_4_full_n,
        if_write => ap_channel_done_pout_local3_7,
        if_dout => pout_local3_4_dout,
        if_empty_n => pout_local3_4_empty_n,
        if_read => Loop_VITIS_LOOP_337_3_proc_U0_ap_ready,
        if_num_data_valid => pout_local3_4_num_data_valid,
        if_fifo_cap => pout_local3_4_fifo_cap);

    pout_local3_5_U : component Macro_MAC_Acc4_top_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_29,
        if_full_n => pout_local3_5_full_n,
        if_write => ap_channel_done_pout_local3_7,
        if_dout => pout_local3_5_dout,
        if_empty_n => pout_local3_5_empty_n,
        if_read => Loop_VITIS_LOOP_337_3_proc_U0_ap_ready,
        if_num_data_valid => pout_local3_5_num_data_valid,
        if_fifo_cap => pout_local3_5_fifo_cap);

    pout_local3_6_U : component Macro_MAC_Acc4_top_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_30,
        if_full_n => pout_local3_6_full_n,
        if_write => ap_channel_done_pout_local3_7,
        if_dout => pout_local3_6_dout,
        if_empty_n => pout_local3_6_empty_n,
        if_read => Loop_VITIS_LOOP_337_3_proc_U0_ap_ready,
        if_num_data_valid => pout_local3_6_num_data_valid,
        if_fifo_cap => pout_local3_6_fifo_cap);

    pout_local3_7_U : component Macro_MAC_Acc4_top_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_VITIS_LOOP_324_2_proc_U0_ap_return_31,
        if_full_n => pout_local3_7_full_n,
        if_write => ap_channel_done_pout_local3_7,
        if_dout => pout_local3_7_dout,
        if_empty_n => pout_local3_7_empty_n,
        if_read => Loop_VITIS_LOOP_337_3_proc_U0_ap_ready,
        if_num_data_valid => pout_local3_7_num_data_valid,
        if_fifo_cap => pout_local3_7_fifo_cap);

    start_for_Loop_VITIS_LOOP_324_2_proc_U0_U : component Macro_MAC_Acc4_top_start_for_Loop_VITIS_LOOP_324_2_proc_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_Loop_VITIS_LOOP_324_2_proc_U0_din,
        if_full_n => start_for_Loop_VITIS_LOOP_324_2_proc_U0_full_n,
        if_write => entry_proc_U0_start_write,
        if_dout => start_for_Loop_VITIS_LOOP_324_2_proc_U0_dout,
        if_empty_n => start_for_Loop_VITIS_LOOP_324_2_proc_U0_empty_n,
        if_read => Loop_VITIS_LOOP_324_2_proc_U0_ap_ready);





    ap_sync_reg_channel_write_pout_local3_7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_pout_local3_7 <= ap_const_logic_0;
            else
                if (((Loop_VITIS_LOOP_324_2_proc_U0_ap_done and Loop_VITIS_LOOP_324_2_proc_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_pout_local3_7 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_pout_local3_7 <= ap_sync_channel_write_pout_local3_7;
                end if; 
            end if;
        end if;
    end process;

    Loop_VITIS_LOOP_324_2_proc_U0_ap_continue <= ap_sync_channel_write_pout_local3_7;
    Loop_VITIS_LOOP_324_2_proc_U0_ap_start <= start_for_Loop_VITIS_LOOP_324_2_proc_U0_empty_n;
    Loop_VITIS_LOOP_337_3_proc_U0_ap_continue <= ap_const_logic_1;
    Loop_VITIS_LOOP_337_3_proc_U0_ap_start <= pout_local0_empty_n;
    ap_channel_done_pout_local3_7 <= ((ap_sync_reg_channel_write_pout_local3_7 xor ap_const_logic_1) and Loop_VITIS_LOOP_324_2_proc_U0_ap_done);
    ap_done <= Loop_VITIS_LOOP_337_3_proc_U0_ap_done;
    ap_idle <= ((pout_local0_empty_n xor ap_const_logic_1) and entry_proc_U0_ap_idle and Loop_VITIS_LOOP_337_3_proc_U0_ap_idle and Loop_VITIS_LOOP_324_2_proc_U0_ap_idle);
    ap_ready <= entry_proc_U0_ap_ready;
    ap_sync_channel_write_pout_local3_7 <= ((pout_local3_7_full_n and ap_channel_done_pout_local3_7) or ap_sync_reg_channel_write_pout_local3_7);
    entry_proc_U0_ap_continue <= ap_const_logic_1;
    entry_proc_U0_ap_start <= ap_start;
    out_r <= Loop_VITIS_LOOP_337_3_proc_U0_out_r;
    out_r_ap_vld <= Loop_VITIS_LOOP_337_3_proc_U0_out_r_ap_vld;
    start_for_Loop_VITIS_LOOP_324_2_proc_U0_din <= (0=>ap_const_logic_1, others=>'-');
end behav;
