-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Macro_MAC_Acc4_top_Loop_VITIS_LOOP_324_2_proc_Pipeline_VITIS_LOOP_154_24 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    mro2_s_M_elems_V_0_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    mro2_s_M_elems_V_0_full_n : IN STD_LOGIC;
    mro2_s_M_elems_V_0_write : OUT STD_LOGIC;
    mro2_s_M_elems_V_4_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    mro2_s_M_elems_V_4_full_n : IN STD_LOGIC;
    mro2_s_M_elems_V_4_write : OUT STD_LOGIC;
    mro2_s_M_elems_V_1_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    mro2_s_M_elems_V_1_full_n : IN STD_LOGIC;
    mro2_s_M_elems_V_1_write : OUT STD_LOGIC;
    mro2_s_M_elems_V_5_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    mro2_s_M_elems_V_5_full_n : IN STD_LOGIC;
    mro2_s_M_elems_V_5_write : OUT STD_LOGIC;
    mro2_s_M_elems_V_2_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    mro2_s_M_elems_V_2_full_n : IN STD_LOGIC;
    mro2_s_M_elems_V_2_write : OUT STD_LOGIC;
    mro2_s_M_elems_V_6_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    mro2_s_M_elems_V_6_full_n : IN STD_LOGIC;
    mro2_s_M_elems_V_6_write : OUT STD_LOGIC;
    mro2_s_M_elems_V_7_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    mro2_s_M_elems_V_7_full_n : IN STD_LOGIC;
    mro2_s_M_elems_V_7_write : OUT STD_LOGIC;
    mro2_s_M_elems_V_3_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    mro2_s_M_elems_V_3_full_n : IN STD_LOGIC;
    mro2_s_M_elems_V_3_write : OUT STD_LOGIC;
    p_0_0_3700_partselect : IN STD_LOGIC_VECTOR (31 downto 0);
    p_0_0_2699_partselect : IN STD_LOGIC_VECTOR (31 downto 0);
    p_0_0_1698_partselect : IN STD_LOGIC_VECTOR (31 downto 0);
    empty : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of Macro_MAC_Acc4_top_Loop_VITIS_LOOP_324_2_proc_Pipeline_VITIS_LOOP_154_24 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal trunc_ln159_reg_229 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter1_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp1_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_grp3 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp3_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp3 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_grp5 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp5_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp5 : BOOLEAN;
    signal icmp_ln160_reg_233 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter1_grp7 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp7_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp7 : BOOLEAN;
    signal icmp_ln154_fu_160_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal mro2_s_M_elems_V_3_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp7 : BOOLEAN;
    signal mro2_s_M_elems_V_2_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp5 : BOOLEAN;
    signal mro2_s_M_elems_V_1_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp3 : BOOLEAN;
    signal mro2_s_M_elems_V_0_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal mro2_s_M_elems_V_4_blk_n : STD_LOGIC;
    signal mro2_s_M_elems_V_5_blk_n : STD_LOGIC;
    signal mro2_s_M_elems_V_6_blk_n : STD_LOGIC;
    signal mro2_s_M_elems_V_7_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp3 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp5 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp7 : BOOLEAN;
    signal trunc_ln159_fu_172_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln160_fu_184_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_fu_68 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln154_fu_166_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_j_3 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp3 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp5 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp7 : BOOLEAN;
    signal or_ln160_2_fu_176_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component Macro_MAC_Acc4_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component Macro_MAC_Acc4_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp1_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1)) then 
                    ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp3_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp3_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp3_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3)) then 
                    ap_block_pp0_stage0_subdone_grp3_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp5_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp5_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp5_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5)) then 
                    ap_block_pp0_stage0_subdone_grp5_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp7_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp7_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp7_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp7)) then 
                    ap_block_pp0_stage0_subdone_grp7_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    j_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln154_fu_160_p2 = ap_const_lv1_0))) then 
                    j_fu_68 <= add_ln154_fu_166_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_68 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln160_reg_233 <= icmp_ln160_fu_184_p2;
                trunc_ln159_reg_229 <= trunc_ln159_fu_172_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln154_fu_166_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j_3) + unsigned(ap_const_lv5_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp1, ap_block_pp0_stage0_subdone_grp1_done_reg)
    begin
                ap_block_pp0_stage0_01001_grp1 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1));
    end process;


    ap_block_pp0_stage0_01001_grp3_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp3, ap_block_pp0_stage0_subdone_grp3_done_reg)
    begin
                ap_block_pp0_stage0_01001_grp3 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp3));
    end process;


    ap_block_pp0_stage0_01001_grp5_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp5, ap_block_pp0_stage0_subdone_grp5_done_reg)
    begin
                ap_block_pp0_stage0_01001_grp5 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp5));
    end process;


    ap_block_pp0_stage0_01001_grp7_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp7, ap_block_pp0_stage0_subdone_grp7_done_reg)
    begin
                ap_block_pp0_stage0_01001_grp7 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp7_done_reg) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp7));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp1, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_state2_pp0_stage0_iter1_grp3, ap_block_pp0_stage0_subdone_grp3_done_reg, ap_block_state2_pp0_stage0_iter1_grp5, ap_block_pp0_stage0_subdone_grp5_done_reg, ap_block_state2_pp0_stage0_iter1_grp7, ap_block_pp0_stage0_subdone_grp7_done_reg)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp3)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp7_done_reg) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp7)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp5))));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp1, ap_block_pp0_stage0_subdone_grp1_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1));
    end process;


    ap_block_pp0_stage0_11001_grp3_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp3, ap_block_pp0_stage0_subdone_grp3_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp3 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp3));
    end process;


    ap_block_pp0_stage0_11001_grp5_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp5, ap_block_pp0_stage0_subdone_grp5_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp5 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp5));
    end process;


    ap_block_pp0_stage0_11001_grp7_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp7, ap_block_pp0_stage0_subdone_grp7_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp7 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp7_done_reg) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp7));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp7 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp1, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_state2_pp0_stage0_iter1_grp3, ap_block_pp0_stage0_subdone_grp3_done_reg, ap_block_state2_pp0_stage0_iter1_grp5, ap_block_pp0_stage0_subdone_grp5_done_reg, ap_block_state2_pp0_stage0_iter1_grp7, ap_block_pp0_stage0_subdone_grp7_done_reg)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp3)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp7_done_reg) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp7)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp5))));
    end process;


    ap_block_pp0_stage0_subdone_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp1, ap_block_pp0_stage0_subdone_grp1_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp1 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1));
    end process;


    ap_block_pp0_stage0_subdone_grp3_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp3, ap_block_pp0_stage0_subdone_grp3_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp3 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp3));
    end process;


    ap_block_pp0_stage0_subdone_grp5_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp5, ap_block_pp0_stage0_subdone_grp5_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp5 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp5));
    end process;


    ap_block_pp0_stage0_subdone_grp7_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp7, ap_block_pp0_stage0_subdone_grp7_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp7 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp7_done_reg) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp7));
    end process;


    ap_block_state2_pp0_stage0_iter1_grp1_assign_proc : process(mro2_s_M_elems_V_0_full_n, mro2_s_M_elems_V_4_full_n, trunc_ln159_reg_229)
    begin
                ap_block_state2_pp0_stage0_iter1_grp1 <= (((trunc_ln159_reg_229 = ap_const_lv1_1) and (mro2_s_M_elems_V_4_full_n = ap_const_logic_0)) or ((trunc_ln159_reg_229 = ap_const_lv1_0) and (mro2_s_M_elems_V_0_full_n = ap_const_logic_0)));
    end process;


    ap_block_state2_pp0_stage0_iter1_grp3_assign_proc : process(mro2_s_M_elems_V_1_full_n, mro2_s_M_elems_V_5_full_n, trunc_ln159_reg_229)
    begin
                ap_block_state2_pp0_stage0_iter1_grp3 <= (((trunc_ln159_reg_229 = ap_const_lv1_1) and (mro2_s_M_elems_V_5_full_n = ap_const_logic_0)) or ((trunc_ln159_reg_229 = ap_const_lv1_0) and (mro2_s_M_elems_V_1_full_n = ap_const_logic_0)));
    end process;


    ap_block_state2_pp0_stage0_iter1_grp5_assign_proc : process(mro2_s_M_elems_V_2_full_n, mro2_s_M_elems_V_6_full_n, trunc_ln159_reg_229)
    begin
                ap_block_state2_pp0_stage0_iter1_grp5 <= (((trunc_ln159_reg_229 = ap_const_lv1_1) and (mro2_s_M_elems_V_6_full_n = ap_const_logic_0)) or ((trunc_ln159_reg_229 = ap_const_lv1_0) and (mro2_s_M_elems_V_2_full_n = ap_const_logic_0)));
    end process;


    ap_block_state2_pp0_stage0_iter1_grp7_assign_proc : process(mro2_s_M_elems_V_7_full_n, mro2_s_M_elems_V_3_full_n, icmp_ln160_reg_233)
    begin
                ap_block_state2_pp0_stage0_iter1_grp7 <= (((mro2_s_M_elems_V_3_full_n = ap_const_logic_0) and (icmp_ln160_reg_233 = ap_const_lv1_1)) or ((mro2_s_M_elems_V_7_full_n = ap_const_logic_0) and (icmp_ln160_reg_233 = ap_const_lv1_0)));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln154_fu_160_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln154_fu_160_p2 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_j_3_assign_proc : process(ap_CS_fsm_pp0_stage0, j_fu_68, ap_loop_init, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_j_3 <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_j_3 <= j_fu_68;
        end if; 
    end process;

    icmp_ln154_fu_160_p2 <= "1" when (ap_sig_allocacmp_j_3 = ap_const_lv5_10) else "0";
    icmp_ln160_fu_184_p2 <= "1" when (or_ln160_2_fu_176_p3 = ap_const_lv3_3) else "0";

    mro2_s_M_elems_V_0_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, mro2_s_M_elems_V_0_full_n, trunc_ln159_reg_229, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (trunc_ln159_reg_229 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            mro2_s_M_elems_V_0_blk_n <= mro2_s_M_elems_V_0_full_n;
        else 
            mro2_s_M_elems_V_0_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    mro2_s_M_elems_V_0_din <= empty;

    mro2_s_M_elems_V_0_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln159_reg_229, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln159_reg_229 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            mro2_s_M_elems_V_0_write <= ap_const_logic_1;
        else 
            mro2_s_M_elems_V_0_write <= ap_const_logic_0;
        end if; 
    end process;


    mro2_s_M_elems_V_1_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, mro2_s_M_elems_V_1_full_n, trunc_ln159_reg_229, ap_block_pp0_stage0_subdone_grp3_done_reg, ap_block_pp0_stage0_grp3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp3) and (trunc_ln159_reg_229 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            mro2_s_M_elems_V_1_blk_n <= mro2_s_M_elems_V_1_full_n;
        else 
            mro2_s_M_elems_V_1_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    mro2_s_M_elems_V_1_din <= p_0_0_1698_partselect;

    mro2_s_M_elems_V_1_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln159_reg_229, ap_block_pp0_stage0_subdone_grp3_done_reg, ap_block_pp0_stage0_11001_grp3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp3) and (trunc_ln159_reg_229 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            mro2_s_M_elems_V_1_write <= ap_const_logic_1;
        else 
            mro2_s_M_elems_V_1_write <= ap_const_logic_0;
        end if; 
    end process;


    mro2_s_M_elems_V_2_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, mro2_s_M_elems_V_2_full_n, trunc_ln159_reg_229, ap_block_pp0_stage0_subdone_grp5_done_reg, ap_block_pp0_stage0_grp5)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp5) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg) and (trunc_ln159_reg_229 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            mro2_s_M_elems_V_2_blk_n <= mro2_s_M_elems_V_2_full_n;
        else 
            mro2_s_M_elems_V_2_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    mro2_s_M_elems_V_2_din <= p_0_0_2699_partselect;

    mro2_s_M_elems_V_2_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln159_reg_229, ap_block_pp0_stage0_subdone_grp5_done_reg, ap_block_pp0_stage0_11001_grp5)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp5) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg) and (trunc_ln159_reg_229 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            mro2_s_M_elems_V_2_write <= ap_const_logic_1;
        else 
            mro2_s_M_elems_V_2_write <= ap_const_logic_0;
        end if; 
    end process;


    mro2_s_M_elems_V_3_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, mro2_s_M_elems_V_3_full_n, icmp_ln160_reg_233, ap_block_pp0_stage0_subdone_grp7_done_reg, ap_block_pp0_stage0_grp7)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp7) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp7_done_reg) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln160_reg_233 = ap_const_lv1_1))) then 
            mro2_s_M_elems_V_3_blk_n <= mro2_s_M_elems_V_3_full_n;
        else 
            mro2_s_M_elems_V_3_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    mro2_s_M_elems_V_3_din <= p_0_0_3700_partselect;

    mro2_s_M_elems_V_3_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln160_reg_233, ap_block_pp0_stage0_subdone_grp7_done_reg, ap_block_pp0_stage0_11001_grp7)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp7) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp7_done_reg) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln160_reg_233 = ap_const_lv1_1))) then 
            mro2_s_M_elems_V_3_write <= ap_const_logic_1;
        else 
            mro2_s_M_elems_V_3_write <= ap_const_logic_0;
        end if; 
    end process;


    mro2_s_M_elems_V_4_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, mro2_s_M_elems_V_4_full_n, trunc_ln159_reg_229, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (trunc_ln159_reg_229 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            mro2_s_M_elems_V_4_blk_n <= mro2_s_M_elems_V_4_full_n;
        else 
            mro2_s_M_elems_V_4_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    mro2_s_M_elems_V_4_din <= empty;

    mro2_s_M_elems_V_4_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln159_reg_229, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln159_reg_229 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            mro2_s_M_elems_V_4_write <= ap_const_logic_1;
        else 
            mro2_s_M_elems_V_4_write <= ap_const_logic_0;
        end if; 
    end process;


    mro2_s_M_elems_V_5_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, mro2_s_M_elems_V_5_full_n, trunc_ln159_reg_229, ap_block_pp0_stage0_subdone_grp3_done_reg, ap_block_pp0_stage0_grp3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp3) and (trunc_ln159_reg_229 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            mro2_s_M_elems_V_5_blk_n <= mro2_s_M_elems_V_5_full_n;
        else 
            mro2_s_M_elems_V_5_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    mro2_s_M_elems_V_5_din <= p_0_0_1698_partselect;

    mro2_s_M_elems_V_5_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln159_reg_229, ap_block_pp0_stage0_subdone_grp3_done_reg, ap_block_pp0_stage0_11001_grp3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp3) and (trunc_ln159_reg_229 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            mro2_s_M_elems_V_5_write <= ap_const_logic_1;
        else 
            mro2_s_M_elems_V_5_write <= ap_const_logic_0;
        end if; 
    end process;


    mro2_s_M_elems_V_6_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, mro2_s_M_elems_V_6_full_n, trunc_ln159_reg_229, ap_block_pp0_stage0_subdone_grp5_done_reg, ap_block_pp0_stage0_grp5)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp5) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg) and (trunc_ln159_reg_229 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            mro2_s_M_elems_V_6_blk_n <= mro2_s_M_elems_V_6_full_n;
        else 
            mro2_s_M_elems_V_6_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    mro2_s_M_elems_V_6_din <= p_0_0_2699_partselect;

    mro2_s_M_elems_V_6_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, trunc_ln159_reg_229, ap_block_pp0_stage0_subdone_grp5_done_reg, ap_block_pp0_stage0_11001_grp5)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp5) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg) and (trunc_ln159_reg_229 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            mro2_s_M_elems_V_6_write <= ap_const_logic_1;
        else 
            mro2_s_M_elems_V_6_write <= ap_const_logic_0;
        end if; 
    end process;


    mro2_s_M_elems_V_7_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, mro2_s_M_elems_V_7_full_n, icmp_ln160_reg_233, ap_block_pp0_stage0_subdone_grp7_done_reg, ap_block_pp0_stage0_grp7)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp7) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp7_done_reg) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln160_reg_233 = ap_const_lv1_0))) then 
            mro2_s_M_elems_V_7_blk_n <= mro2_s_M_elems_V_7_full_n;
        else 
            mro2_s_M_elems_V_7_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    mro2_s_M_elems_V_7_din <= p_0_0_3700_partselect;

    mro2_s_M_elems_V_7_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln160_reg_233, ap_block_pp0_stage0_subdone_grp7_done_reg, ap_block_pp0_stage0_11001_grp7)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp7) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp7_done_reg) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln160_reg_233 = ap_const_lv1_0))) then 
            mro2_s_M_elems_V_7_write <= ap_const_logic_1;
        else 
            mro2_s_M_elems_V_7_write <= ap_const_logic_0;
        end if; 
    end process;

    or_ln160_2_fu_176_p3 <= (trunc_ln159_fu_172_p1 & ap_const_lv2_3);
    trunc_ln159_fu_172_p1 <= ap_sig_allocacmp_j_3(1 - 1 downto 0);
end behav;
