domain_path: E:\Desktop\LLM\competition\FPGA_GC\KV260\vitis_project\accelerate_wrapper\export\accelerate_wrapper\sw\standalone_psu_cortexa53_0
app_src_dir: E:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
