// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Macro_MAC_Acc4_top_entry_proc (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        xi,
        xi_c_din,
        xi_c_full_n,
        xi_c_write,
        xi_c_num_data_valid,
        xi_c_fifo_cap,
        mro0,
        mro0_c_din,
        mro0_c_full_n,
        mro0_c_write,
        mro0_c_num_data_valid,
        mro0_c_fifo_cap,
        mro1,
        mro1_c_din,
        mro1_c_full_n,
        mro1_c_write,
        mro1_c_num_data_valid,
        mro1_c_fifo_cap,
        mro2,
        mro2_c_din,
        mro2_c_full_n,
        mro2_c_write,
        mro2_c_num_data_valid,
        mro2_c_fifo_cap,
        mro3,
        mro3_c_din,
        mro3_c_full_n,
        mro3_c_write,
        mro3_c_num_data_valid,
        mro3_c_fifo_cap,
        row,
        row_c_din,
        row_c_full_n,
        row_c_write,
        row_c_num_data_valid,
        row_c_fifo_cap
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [127:0] xi;
output  [127:0] xi_c_din;
input   xi_c_full_n;
output   xi_c_write;
input  [2:0] xi_c_num_data_valid;
input  [2:0] xi_c_fifo_cap;
input  [127:0] mro0;
output  [127:0] mro0_c_din;
input   mro0_c_full_n;
output   mro0_c_write;
input  [2:0] mro0_c_num_data_valid;
input  [2:0] mro0_c_fifo_cap;
input  [127:0] mro1;
output  [127:0] mro1_c_din;
input   mro1_c_full_n;
output   mro1_c_write;
input  [2:0] mro1_c_num_data_valid;
input  [2:0] mro1_c_fifo_cap;
input  [127:0] mro2;
output  [127:0] mro2_c_din;
input   mro2_c_full_n;
output   mro2_c_write;
input  [2:0] mro2_c_num_data_valid;
input  [2:0] mro2_c_fifo_cap;
input  [127:0] mro3;
output  [127:0] mro3_c_din;
input   mro3_c_full_n;
output   mro3_c_write;
input  [2:0] mro3_c_num_data_valid;
input  [2:0] mro3_c_fifo_cap;
input  [15:0] row;
output  [15:0] row_c_din;
input   row_c_full_n;
output   row_c_write;
input  [2:0] row_c_num_data_valid;
input  [2:0] row_c_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg xi_c_write;
reg mro0_c_write;
reg mro1_c_write;
reg mro2_c_write;
reg mro3_c_write;
reg row_c_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    xi_c_blk_n;
reg    mro0_c_blk_n;
reg    mro1_c_blk_n;
reg    mro2_c_blk_n;
reg    mro3_c_blk_n;
reg    row_c_blk_n;
reg    ap_block_state1;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        mro0_c_blk_n = mro0_c_full_n;
    end else begin
        mro0_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        mro0_c_write = 1'b1;
    end else begin
        mro0_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        mro1_c_blk_n = mro1_c_full_n;
    end else begin
        mro1_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        mro1_c_write = 1'b1;
    end else begin
        mro1_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        mro2_c_blk_n = mro2_c_full_n;
    end else begin
        mro2_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        mro2_c_write = 1'b1;
    end else begin
        mro2_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        mro3_c_blk_n = mro3_c_full_n;
    end else begin
        mro3_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        mro3_c_write = 1'b1;
    end else begin
        mro3_c_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        row_c_blk_n = row_c_full_n;
    end else begin
        row_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        row_c_write = 1'b1;
    end else begin
        row_c_write = 1'b0;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        xi_c_blk_n = xi_c_full_n;
    end else begin
        xi_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        xi_c_write = 1'b1;
    end else begin
        xi_c_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (row_c_full_n == 1'b0) | (mro3_c_full_n == 1'b0) | (mro2_c_full_n == 1'b0) | (mro1_c_full_n == 1'b0) | (mro0_c_full_n == 1'b0) | (xi_c_full_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign mro0_c_din = mro0;

assign mro1_c_din = mro1;

assign mro2_c_din = mro2;

assign mro3_c_din = mro3;

assign row_c_din = row;

assign start_out = real_start;

assign xi_c_din = xi;

endmodule //Macro_MAC_Acc4_top_entry_proc
