# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/xiping/workspace/kv260_rtl_kernel_test_vitis/rtl_kernel_test_100M_kernels/vivado_rtl_kernel/w4a8_gemm_ex/w4a8_gemm_ex.srcs/sources_1/ip/ip_scaler_dsp_v/ip_scaler_dsp_v.xci
# IP: The module: 'ip_scaler_dsp_v' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/xiping/workspace/kv260_rtl_kernel_test_vitis/rtl_kernel_test_100M_kernels/vivado_rtl_kernel/w4a8_gemm_ex/w4a8_gemm_ex.gen/sources_1/ip/ip_scaler_dsp_v/ip_scaler_dsp_v_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_scaler_dsp_v'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/xiping/workspace/kv260_rtl_kernel_test_vitis/rtl_kernel_test_100M_kernels/vivado_rtl_kernel/w4a8_gemm_ex/w4a8_gemm_ex.srcs/sources_1/ip/ip_scaler_dsp_v/ip_scaler_dsp_v.xci
# IP: The module: 'ip_scaler_dsp_v' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/xiping/workspace/kv260_rtl_kernel_test_vitis/rtl_kernel_test_100M_kernels/vivado_rtl_kernel/w4a8_gemm_ex/w4a8_gemm_ex.gen/sources_1/ip/ip_scaler_dsp_v/ip_scaler_dsp_v_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_scaler_dsp_v'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
